site_name: CAM-SIMA
repo_url: https://github.com/ESCOMP/CAM-SIMA-docs
repo_name: CAM-SIMA-docs
edit_uri: edit/main/docs
nav:
  - Home: index.md
  - Conversion:
    - conversion/conversion-background.md
    - conversion/convert-portable-layer.md
    - conversion/create-metadata.md
    - conversion/create-namelist-xml.md
    - conversion/interstitials.md
    - conversion/create-sdf.md
    - conversion/create-snapshots.md
    - conversion/check-metadata.md
    - conversion/run-cam-sima.md
    - conversion/back-to-cam.md
    - conversion/final-steps.md
    - conversion/walkthrough.md
  - Design:
    - design/cam-build-process.md
    - design/cam-run-process.md
    - design/ccpp-in-cam-sima.md
    - design/constituents.md
    - design/directory-structure.md
    - design/history.md
    - design/sima-design-goals.md
  - Development:
    - development/cam-sima-workflow.md
    - development/cam-coding-standards.md
    - development/cam-testing.md
    - development/debugging.md
    - development/git-basics.md
    - development/git-faq.md
    - development/git-fleximod.md
    - development/tool-recommendations.md
  - Usage:
    - usage/creating-a-case.md
    - usage/history.md
  - Atmospheric_physics:
    - atmospheric_physics/directory-structure.md
    - atmospheric_physics/development_workflow.md
    - atmospheric_physics/Tagging-Instructions.md

plugins:
  - search
  # Date plugin requires fetch-depth: 0
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: !ENV [CI, false]
  - git-committers:
      repository: ESCOMP/CAM-SIMA-docs
      branch: main
      enabled: !ENV [CI, false]

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      info: material/arrow-up-down-bold
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  name: material
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view

markdown_extensions:
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition

extra_css:
  - stylesheets/extra.css
