check_topography_data – MPAS Dynamical Core
check_topography_data Subroutine
51 statements
Source File
subroutine check_topography_data(pio_file)
Uses
dyn_mpas_procedures
dynconst
shr_kind_mod
cam_field_read
cam_logfile
cam_abortutils
pio
dyn_grid
Check for consistency in topography data. The presence of topography file is inferred from the pio_file pointer. If topography file is used, check that the "PHIS" variable, which denotes surface geopotential, is consistent with the surface geometric height in MPAS. Otherwise, if topography file is not used, check that the surface geometric height in MPAS is zero. (KCW, 2024-05-10)
Arguments
Type Intent Optional Attributes Name
type(file_desc_t), intent(in), pointer :: pio_file
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=len_cx), private :: cerr
real(kind=kind_r8), private, parameter :: error_tolerance = 1.0e-3_kind_r8
integer, private :: ierr
character(len=*), private, parameter :: subname = 'dyn_comp::check_topography_data'
logical, private :: success
real(kind=kind_r8), private, allocatable :: surface_geometric_height(:)
real(kind=kind_r8), private, allocatable :: surface_geopotential(:)
real(kind=kind_dyn_mpas), private, pointer :: zgrid(:,:)
Source Code
    subroutine check_topography_data(pio_file)
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: check_allocate, endrun
        use cam_field_read, only: cam_read_field
        use cam_logfile, only: debug_output, debugout_debug, debugout_none, debugout_verbose
        use dyn_grid, only: ncells_solve
        use dynconst, only: constant_g => gravit
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: kind_r8 => shr_kind_r8, &
                                len_cx => shr_kind_cx
        ! Module(s) from external libraries.
        use pio, only: file_desc_t, pio_file_is_open
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: almost_equal
        type(file_desc_t), pointer, intent(in) :: pio_file
        character(*), parameter :: subname = 'dyn_comp::check_topography_data'
        character(len_cx) :: cerr
        integer :: ierr
        logical :: success
        real(kind_r8), parameter :: error_tolerance = 1.0E-3_kind_r8 ! Error tolerance for consistency check.
        real(kind_r8), allocatable :: surface_geometric_height(:)    ! Computed from topography file.
        real(kind_r8), allocatable :: surface_geopotential(:)        ! Read from topography file.
        real(kind_dyn_mpas), pointer :: zgrid(:, :)                  ! From MPAS. Geometric height (m) at layer interfaces.
        call dyn_debug_print(debugout_debug, subname // ' entered')
        nullify(zgrid)
        call mpas_dynamical_core % get_variable_pointer(zgrid, 'mesh', 'zgrid')
        if (associated(pio_file)) then
            call dyn_debug_print(debugout_verbose, 'Topography file is used for consistency check')
            if (.not. pio_file_is_open(pio_file)) then
                call endrun('Invalid PIO file descriptor', subname, __LINE__)
            end if
            allocate(surface_geopotential(ncells_solve), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, 'surface_geopotential(ncells_solve)', &
                file='dyn_comp', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(surface_geometric_height(ncells_solve), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, 'surface_geometric_height(ncells_solve)', &
                file='dyn_comp', line=__LINE__, errmsg=trim(adjustl(cerr)))
            surface_geopotential(:) = 0.0_kind_r8
            surface_geometric_height(:) = 0.0_kind_r8
            call cam_read_field('PHIS', pio_file, surface_geopotential, success, &
                gridname='cam_cell', timelevel=1, log_output=(debug_output > debugout_none))
            if (.not. success) then
                call endrun('Failed to find variable "PHIS"', subname, __LINE__)
            end if
            surface_geometric_height(:) = surface_geopotential(:) / constant_g
            ! Surface geometric height in MPAS should match the values in topography file.
            if (.not. all(almost_equal( &
                real(zgrid(1, 1:ncells_solve), kind_r8), surface_geometric_height, &
                relative_tolerance=error_tolerance))) then
                call endrun('Surface geometric height in MPAS is not consistent with topography data', subname, __LINE__)
            end if
            deallocate(surface_geopotential)
            deallocate(surface_geometric_height)
        else
            call dyn_debug_print(debugout_verbose, 'Topography file is not used for consistency check')
            ! Surface geometric height in MPAS should be zero.
            if (.not. all(almost_equal( &
                real(zgrid(1, 1:ncells_solve), kind_r8), 0.0_kind_r8, &
                relative_tolerance=error_tolerance))) then
                call endrun('Surface geometric height in MPAS is not zero', subname, __LINE__)
            end if
        end if
        nullify(zgrid)
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine check_topography_data
Call graph
check_topography_data calls cam_read_field, check_allocate, endrun, almost_equal, dyn_debug_print, get_variable_pointer, pio_file_is_open
almost_equal calls almost_equal_real32, almost_equal_real64
dyn_debug_print calls dyn_debug_print, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_init calls check_topography_data, dyn_init