dyn_mpas_get_pool_pointer – MPAS Dynamical Core
dyn_mpas_get_pool_pointer Subroutine
Kuan-Chih Wang
2024-03-21
24 statements
Source File
private subroutine dyn_mpas_get_pool_pointer(self, pool_pointer, pool_name)
Uses
mpas_derived_types
mpas_pool_routines
This subroutine returns a pointer of mpas_pool_type to the named pool. Supported pool names include: "all", "cfg", "dim", and a subset of the var_struct elements in MPAS registry. It is mostly used by the dyn_mpas_get_variable_{pointer,value}_* subroutines to draw a variable from a pool.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
type(mpas_pool_type), intent(out), pointer :: pool_pointer
character(len=*), intent(in) :: pool_name
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_pool_pointer'
Source Code
    subroutine dyn_mpas_get_pool_pointer(self, pool_pointer, pool_name)
        ! Module(s) from MPAS.
        use mpas_derived_types, only: mpas_pool_type
        use mpas_pool_routines, only: mpas_pool_get_subpool
        class(mpas_dynamical_core_type), intent(in) :: self
        type(mpas_pool_type), pointer, intent(out) :: pool_pointer
        character(*), intent(in) :: pool_name
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_pool_pointer'
        nullify(pool_pointer)
        select case (trim(adjustl(pool_name)))
            case ('all')
                pool_pointer => self % domain_ptr % blocklist % allfields
            case ('cfg')
                pool_pointer => self % domain_ptr % configs
            case ('dim')
                pool_pointer => self % domain_ptr % blocklist % dimensions
            case ('diag', 'mesh', 'state', 'tend', 'tend_physics')
                call mpas_pool_get_subpool(self % domain_ptr % blocklist % allstructs, trim(adjustl(pool_name)), pool_pointer)
            case default
                call self % model_error('Unsupported pool name "' // trim(adjustl(pool_name)) // '"', subname, __LINE__)
        end select
        if (.not. associated(pool_pointer)) then
            call self % model_error('Failed to find pool "' // trim(adjustl(pool_name)) // '"', subname, __LINE__)
        end if
    end subroutine dyn_mpas_get_pool_pointer
Call graph
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_compute_unit_vector calls dyn_mpas_get_pool_pointer, get_variable_pointer
dyn_mpas_define_scalar calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer
dyn_mpas_init_phase3 calls dyn_mpas_get_pool_pointer
dyn_mpas_init_phase4 calls dyn_mpas_get_pool_pointer, get_variable_pointer
dyn_mpas_run calls dyn_mpas_get_pool_pointer, get_variable_pointer
dyn_init calls dyn_mpas_define_scalar, dyn_mpas_init_phase4, check_topography_data, dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
dyn_run calls dyn_mpas_run, dyn_run
model_grid_init calls dyn_mpas_compute_unit_vector, dyn_mpas_init_phase3, define_cam_grid, init_physics_grid, init_reference_pressure, dyn_inquire_mesh_dimensions, model_grid_init
check_topography_data calls get_variable_pointer
define_cam_grid calls get_variable_pointer
dyn_exchange_constituent_states calls get_variable_pointer, dyn_exchange_constituent_states
dyn_mpas_compute_cell_relative_vorticity calls get_variable_pointer
dyn_mpas_compute_edge_wind calls get_variable_pointer
dyn_mpas_get_global_mesh_dimension calls get_variable_pointer
dyn_mpas_get_local_mesh_dimension calls get_variable_pointer
dyn_mpas_get_variable_value_c0 calls get_variable_pointer
dyn_mpas_get_variable_value_c1 calls get_variable_pointer
dyn_mpas_get_variable_value_i0 calls get_variable_pointer
dyn_mpas_get_variable_value_i1 calls get_variable_pointer
dyn_mpas_get_variable_value_i2 calls get_variable_pointer
dyn_mpas_get_variable_value_i3 calls get_variable_pointer
dyn_mpas_get_variable_value_l0 calls get_variable_pointer
dyn_mpas_get_variable_value_r0 calls get_variable_pointer
dyn_mpas_get_variable_value_r1 calls get_variable_pointer
dyn_mpas_get_variable_value_r2 calls get_variable_pointer
dyn_mpas_get_variable_value_r3 calls get_variable_pointer
dyn_mpas_get_variable_value_r4 calls get_variable_pointer
dyn_mpas_get_variable_value_r5 calls get_variable_pointer
dyn_mpas_read_namelist calls get_variable_pointer
dyn_variable_dump calls get_variable_pointer
init_physics_grid calls get_variable_pointer
init_reference_pressure calls get_variable_pointer
dyn_final calls dyn_variable_dump, dyn_final
dyn_inquire_mesh_dimensions calls dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension, dyn_inquire_mesh_dimensions
dyn_readnl calls dyn_mpas_read_namelist, dyn_readnl
dynamics_to_physics_coupling calls init_shared_variables, dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
physics_to_dynamics_coupling calls init_shared_variables, set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru, dyn_exchange_constituent_states, physics_to_dynamics_coupling
set_analytic_initial_condition calls init_shared_variables, set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u, set_mpas_state_w
stepon_run3 calls dyn_run
stepon_final calls dyn_final
stepon_run2 calls physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling