dyn_variable_dump – MPAS Dynamical Core
dyn_variable_dump Subroutine
38 statements
Source File
subroutine dyn_variable_dump()
Uses
shr_kind_mod
shr_pio_mod
cam_instance
cam_abortutils
dyn_grid
physics_types
pio
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=len_cx), private :: cerr
integer, private :: ierr
type(file_desc_t), private, pointer :: pio_file
integer, private :: pio_ioformat
type(iosystem_desc_t), private, pointer :: pio_iosystem
integer, private :: pio_iotype
character(len=*), private, parameter :: subname = 'dyn_comp::dyn_variable_dump'
real(kind=kind_dyn_mpas), private, pointer :: surface_pressure(:)
Source Code
    subroutine dyn_variable_dump()
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: check_allocate, endrun
        use cam_instance, only: atm_id
        use dyn_grid, only: ncells_solve
        use physics_types, only: phys_state
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: len_cx => shr_kind_cx
        use shr_pio_mod, only: shr_pio_getioformat, shr_pio_getiosys, shr_pio_getiotype
        ! Module(s) from external libraries.
        use pio, only: file_desc_t, iosystem_desc_t, pio_createfile, pio_closefile, pio_clobber, pio_noerr
        character(*), parameter :: subname = 'dyn_comp::dyn_variable_dump'
        character(len_cx) :: cerr
        integer :: ierr
        integer :: pio_ioformat, pio_iotype
        real(kind_dyn_mpas), pointer :: surface_pressure(:)
        type(file_desc_t), pointer :: pio_file
        type(iosystem_desc_t), pointer :: pio_iosystem
        nullify(pio_file)
        nullify(pio_iosystem)
        nullify(surface_pressure)
        call mpas_dynamical_core % get_variable_pointer(surface_pressure, 'diag', 'surface_pressure')
        surface_pressure(1:ncells_solve) = real(phys_state % ps(:), kind_dyn_mpas)
        nullify(surface_pressure)
        call mpas_dynamical_core % exchange_halo('surface_pressure')
        allocate(pio_file, errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'pio_file', &
            file='dyn_comp', line=__LINE__, errmsg=trim(adjustl(cerr)))
        pio_iosystem => shr_pio_getiosys(atm_id)
        pio_ioformat = shr_pio_getioformat(atm_id)
        pio_ioformat = ior(pio_ioformat, pio_clobber)
        pio_iotype = shr_pio_getiotype(atm_id)
        ierr = pio_createfile(pio_iosystem, pio_file, pio_iotype, 'dyn_variable_dump.nc', pio_ioformat)
        if (ierr /= pio_noerr) then
            call endrun('Failed to create file for variable dumping', subname, __LINE__)
        end if
        call mpas_dynamical_core % read_write_stream(pio_file, 'w', 'invariant+input+restart+output')
        call pio_closefile(pio_file)
        deallocate(pio_file)
        nullify(pio_file)
        nullify(pio_iosystem)
    end subroutine dyn_variable_dump
Call graph
dyn_variable_dump calls check_allocate, endrun, get_variable_pointer, pio_closefile, pio_createfile, dyn_mpas_exchange_halo, dyn_mpas_read_write_stream, ps, shr_pio_getioformat, shr_pio_getiosys, shr_pio_getiotype
dyn_mpas_exchange_halo calls mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info, dyn_mpas_debug_print, stringify
dyn_mpas_read_write_stream calls dyn_mpas_exchange_halo, mpas_closestream, mpas_pool_destroy_pool, mpas_readstream, mpas_writestream, postread_reindex, postwrite_reindex, prewrite_reindex, dyn_mpas_debug_print, dyn_mpas_init_stream_with_pool, parse_stream_name
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_init_stream_with_pool calls mpas_pool_get_field, dyn_mpas_debug_print, parse_stream_name, stringify, mpas_createstream, mpas_pool_add_config, mpas_pool_create_pool, mpas_streamaddfield, add_stream_attribute, pio_file_is_open, dyn_mpas_check_variable_status
parse_stream_name calls tokenize, index_unique, parse_stream_name_fragment
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
dyn_mpas_check_variable_status calls mpas_pool_get_field, dyn_mpas_debug_print, stringify, pio_file_is_open, constituentnames, pio_inq_varid, pio_inq_varndims, pio_inq_vartype
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
tokenize_into_first_last calls split
tokenize_into_tokens_separator calls tokenize
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final