dyn_mpas_map_constituent_index – MPAS Dynamical Core
dyn_mpas_map_constituent_index Function
Kuan-Chih Wang
2024-05-16
14 statements
Source File
private pure function dyn_mpas_map_constituent_index(self, mpas_scalar_index) result(constituent_index)
This function returns the constituent index that corresponds to the given MPAS scalar index. In case of errors, zero is produced.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(in) :: mpas_scalar_index
Return Value integer
Called by
Source Code
    pure function dyn_mpas_map_constituent_index(self, mpas_scalar_index) result(constituent_index)
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, intent(in) :: mpas_scalar_index
        integer :: constituent_index
        ! Catch segmentation fault.
        if (.not. allocated(self % index_mpas_scalar_to_constituent)) then
            constituent_index = 0
            return
        end if
        if (mpas_scalar_index < lbound(self % index_mpas_scalar_to_constituent, 1) .or. &
            mpas_scalar_index > ubound(self % index_mpas_scalar_to_constituent, 1)) then
            constituent_index = 0
            return
        end if
        constituent_index = self % index_mpas_scalar_to_constituent(mpas_scalar_index)
    end function dyn_mpas_map_constituent_index
Call graph
dyn_exchange_constituent_states calls dyn_mpas_map_constituent_index, dyn_exchange_constituent_states
dynamics_to_physics_coupling calls set_physics_state_external, dyn_exchange_constituent_states, dynamics_to_physics_coupling
set_analytic_initial_condition calls set_mpas_state_scalars
dyn_init calls dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
physics_to_dynamics_coupling calls dyn_exchange_constituent_states, physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling
stepon_run2 calls physics_to_dynamics_coupling