dyn_mpas_map_mpas_scalar_index – MPAS Dynamical Core
dyn_mpas_map_mpas_scalar_index Function
Kuan-Chih Wang
2024-05-16
14 statements
Source File
private pure function dyn_mpas_map_mpas_scalar_index(self, constituent_index) result(mpas_scalar_index)
This function returns the MPAS scalar index that corresponds to the given constituent index. In case of errors, zero is produced.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(in) :: constituent_index
Return Value integer
Called by
Source Code
    pure function dyn_mpas_map_mpas_scalar_index(self, constituent_index) result(mpas_scalar_index)
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, intent(in) :: constituent_index
        integer :: mpas_scalar_index
        ! Catch segmentation fault.
        if (.not. allocated(self % index_constituent_to_mpas_scalar)) then
            mpas_scalar_index = 0
            return
        end if
        if (constituent_index < lbound(self % index_constituent_to_mpas_scalar, 1) .or. &
            constituent_index > ubound(self % index_constituent_to_mpas_scalar, 1)) then
            mpas_scalar_index = 0
            return
        end if
        mpas_scalar_index = self % index_constituent_to_mpas_scalar(constituent_index)
    end function dyn_mpas_map_mpas_scalar_index
Call graph
dyn_exchange_constituent_states calls dyn_mpas_map_mpas_scalar_index, dyn_exchange_constituent_states
set_thermodynamic_active_species_mapping calls dyn_mpas_map_mpas_scalar_index
dyn_init calls set_thermodynamic_active_species_mapping, dyn_exchange_constituent_states, dyn_init
dynamics_to_physics_coupling calls init_shared_variables, dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
physics_to_dynamics_coupling calls dyn_exchange_constituent_states, physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling
stepon_run2 calls physics_to_dynamics_coupling