dyn_mpas_get_variable_pointer_l0 – MPAS Dynamical Core
dyn_mpas_get_variable_pointer_l0 Subroutine
21 statements
Source File
private subroutine dyn_mpas_get_variable_pointer_l0(self, variable_pointer, pool_name, variable_name, time_level)
Uses
mpas_derived_types
mpas_pool_routines
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
logical, intent(out), pointer :: variable_pointer
character(len=*), intent(in) :: pool_name
character(len=*), intent(in) :: variable_name
integer, intent(in), optional :: time_level
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(mpas_pool_type), private, pointer :: mpas_pool
character(len=*), private, parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_variable_pointer_l0'
Source Code
    subroutine dyn_mpas_get_variable_pointer_l0(self, variable_pointer, pool_name, variable_name, time_level)
        ! Module(s) from MPAS.
        use mpas_derived_types, only: mpas_pool_type
        use mpas_pool_routines, only: mpas_pool_get_config
        class(mpas_dynamical_core_type), intent(in) :: self
        logical, pointer, intent(out) :: variable_pointer
        character(*), intent(in) :: pool_name
        character(*), intent(in) :: variable_name
        integer, optional, intent(in) :: time_level
        character(*), parameter :: subname = 'dyn_mpas_subdriver::dyn_mpas_get_variable_pointer_l0'
        type(mpas_pool_type), pointer :: mpas_pool
        nullify(mpas_pool)
        call self % get_pool_pointer(mpas_pool, pool_name)
        nullify(variable_pointer)
        if (trim(adjustl(pool_name)) == 'cfg') then
            ! Special case for config-related variables. They must be retrieved by calling `mpas_pool_get_config`.
            call mpas_pool_get_config(mpas_pool, trim(adjustl(variable_name)), variable_pointer)
        end if
        if (.not. associated(variable_pointer)) then
            call self % model_error('Failed to find variable "' // trim(adjustl(variable_name)) // '"', subname, __LINE__)
        end if
        nullify(mpas_pool)
    end subroutine dyn_mpas_get_variable_pointer_l0
Call graph
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
check_topography_data calls get_variable_pointer
define_cam_grid calls get_variable_pointer
dyn_exchange_constituent_states calls get_variable_pointer, dyn_exchange_constituent_states
dyn_mpas_compute_cell_relative_vorticity calls get_variable_pointer
dyn_mpas_compute_edge_wind calls get_variable_pointer
dyn_mpas_compute_unit_vector calls get_variable_pointer
dyn_mpas_get_global_mesh_dimension calls get_variable_pointer
dyn_mpas_get_local_mesh_dimension calls get_variable_pointer
dyn_mpas_get_variable_value_c0 calls get_variable_pointer
dyn_mpas_get_variable_value_c1 calls get_variable_pointer
dyn_mpas_get_variable_value_i0 calls get_variable_pointer
dyn_mpas_get_variable_value_i1 calls get_variable_pointer
dyn_mpas_get_variable_value_i2 calls get_variable_pointer
dyn_mpas_get_variable_value_i3 calls get_variable_pointer
dyn_mpas_get_variable_value_l0 calls get_variable_pointer
dyn_mpas_get_variable_value_r0 calls get_variable_pointer
dyn_mpas_get_variable_value_r1 calls get_variable_pointer
dyn_mpas_get_variable_value_r2 calls get_variable_pointer
dyn_mpas_get_variable_value_r3 calls get_variable_pointer
dyn_mpas_get_variable_value_r4 calls get_variable_pointer
dyn_mpas_get_variable_value_r5 calls get_variable_pointer
dyn_mpas_init_phase4 calls get_variable_pointer
dyn_mpas_read_namelist calls get_variable_pointer
dyn_mpas_run calls get_variable_pointer
dyn_variable_dump calls get_variable_pointer
init_physics_grid calls get_variable_pointer
init_reference_pressure calls get_variable_pointer
dyn_final calls dyn_variable_dump, dyn_final
dyn_init calls check_topography_data, dyn_mpas_init_phase4, dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
dyn_inquire_mesh_dimensions calls dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension, dyn_inquire_mesh_dimensions
dyn_readnl calls dyn_mpas_read_namelist, dyn_readnl
dyn_run calls dyn_mpas_run, dyn_run
dynamics_to_physics_coupling calls init_shared_variables, dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
model_grid_init calls define_cam_grid, dyn_mpas_compute_unit_vector, init_physics_grid, init_reference_pressure, dyn_inquire_mesh_dimensions, model_grid_init
physics_to_dynamics_coupling calls init_shared_variables, set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru, dyn_exchange_constituent_states, physics_to_dynamics_coupling
set_analytic_initial_condition calls init_shared_variables, set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u, set_mpas_state_w
stepon_final calls dyn_final
stepon_run2 calls physics_to_dynamics_coupling
stepon_run3 calls dyn_run
stepon_timestep_init calls dynamics_to_physics_coupling