dyn_inquire_advected_constituent_index – MPAS Dynamical Core
dyn_inquire_advected_constituent_index Subroutine
23 statements
Source File
subroutine dyn_inquire_advected_constituent_index()
Uses
shr_kind_mod
string_utils
cam_logfile
cam_constituents
cam_abortutils
CAM-SIMA holds information about all constituents. However, MPAS dynamical core only knows about the advected ones. Inquire the index mapping for constituents advected by MPAS dynamical core. Save it as the advected_constituent_index lookup table, which serves as the authoritative source for mapping an index within the set of advected constituents to an index within the set of all constituents. (KCW, 2026-03-25)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=len_cx), private :: cerr
integer, private :: i
integer, private :: ierr
integer, private :: j
character(len=*), private, parameter :: subname = 'dyn_comp::dyn_inquire_advected_constituent_index'
Source Code
    subroutine dyn_inquire_advected_constituent_index()
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: check_allocate
        use cam_constituents, only: const_is_advected, &
                                    num_constituents, num_advected
        use cam_logfile, only: debugout_debug
        use string_utils, only: stringify
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: len_cx => shr_kind_cx
        character(*), parameter :: subname = 'dyn_comp::dyn_inquire_advected_constituent_index'
        character(len_cx) :: cerr
        integer :: i, j
        integer :: ierr
        call dyn_debug_print(debugout_debug, subname // ' entered')
        ! This is a protected module variable.
        allocate(advected_constituent_index(num_advected), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'advected_constituent_index(num_advected)', &
            file='dyn_comp', line=__LINE__, errmsg=trim(adjustl(cerr)))
        j = 1
        do i = 1, num_constituents
            ! Skip non-advected constituents.
            if (const_is_advected(i)) then
                advected_constituent_index(j) = i
                j = j + 1
            end if
        end do
        call dyn_debug_print(debugout_debug, 'advected_constituent_index = [' // &
            stringify(advected_constituent_index) // ']')
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine dyn_inquire_advected_constituent_index
Call graph
dyn_inquire_advected_constituent_index calls check_allocate, const_is_advected, dyn_debug_print, stringify
dyn_debug_print calls dyn_debug_print, stringify
dyn_init calls dyn_inquire_advected_constituent_index, dyn_init