dyn_debug_print – MPAS Dynamical Core
dyn_debug_print Module Subroutine
21 statements
Source File
module subroutine dyn_debug_print(level, message, printer) Interface →
Uses
spmd_utils
string_utils
cam_logfile
Print a debug message at a debug level. The debug message will be prefixed by "MPAS Interface (N): ", where N is the MPI rank. The debug level is one of the debugout_* constants from the cam_logfile module. If printer is not supplied, the MPI root rank will print. Otherwise, the designated MPI rank will print instead. (KCW, 2024-02-03)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: level
character(len=*), intent(in) :: message
integer, intent(in), optional :: printer
Calls
Called by
Source Code
    module subroutine dyn_debug_print(level, message, printer)
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debug_output, iulog
        use spmd_utils, only: iam, masterproc
        use string_utils, only: stringify
        integer, intent(in) :: level
        character(*), intent(in) :: message
        integer, optional, intent(in) :: printer
        ! Bail out early if the log level is less verbose than the debug level.
        if (debug_output < level) then
            return
        end if
        if (present(printer)) then
            if (iam /= printer) then
                return
            end if
        else
            if (.not. masterproc) then
                return
            end if
        end if
        write(iulog, '(a)') 'MPAS Interface (' // stringify([iam]) // '): ' // message
    end subroutine dyn_debug_print
Call graph
dyn_debug_print calls stringify, dyn_debug_print
check_topography_data calls dyn_debug_print
define_cam_grid calls dyn_debug_print
dyn_exchange_constituent_states calls dyn_debug_print, dyn_exchange_constituent_states
dyn_final calls dyn_debug_print, dyn_final
dyn_init calls dyn_debug_print, check_topography_data, dyn_inquire_advected_constituent_index, mark_variables_as_initialized, set_analytic_initial_condition, set_thermodynamic_active_species_mapping, set_thermodynamic_energy_formula, dyn_exchange_constituent_states, dyn_init
dyn_inquire_advected_constituent_index calls dyn_debug_print
dyn_inquire_mesh_dimensions calls dyn_debug_print
dyn_readnl calls dyn_debug_print, dyn_readnl
dyn_run calls dyn_debug_print, dyn_run
dynamics_to_physics_coupling calls dyn_debug_print, init_shared_variables, set_physics_state_external, dyn_exchange_constituent_states, dynamics_to_physics_coupling
init_physics_grid calls dyn_debug_print
init_reference_pressure calls dyn_debug_print
mark_variables_as_initialized calls dyn_debug_print
model_grid_init calls dyn_debug_print, define_cam_grid, dyn_inquire_mesh_dimensions, init_physics_grid, init_reference_pressure, model_grid_init
physics_to_dynamics_coupling calls dyn_debug_print, init_shared_variables, set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru, dyn_exchange_constituent_states, physics_to_dynamics_coupling
set_analytic_initial_condition calls dyn_debug_print, init_shared_variables, set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u, set_mpas_state_w
set_thermodynamic_active_species_mapping calls dyn_debug_print
set_thermodynamic_energy_formula calls dyn_debug_print
stepon_final calls dyn_final
stepon_run2 calls physics_to_dynamics_coupling
stepon_run3 calls dyn_run
stepon_timestep_init calls dynamics_to_physics_coupling