dyn_final – MPAS Dynamical Core
dyn_final Module Subroutine
9 statements
Source File
module subroutine dyn_final() Interface →
Uses
cam_logfile
Finalize MPAS dynamical core as well as its framework. (KCW, 2024-10-04)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=*), private, parameter :: subname = 'dyn_comp::dyn_final'
Source Code
    module subroutine dyn_final()
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debugout_debug, debugout_info
        character(*), parameter :: subname = 'dyn_comp::dyn_final'
        call dyn_debug_print(debugout_debug, subname // ' entered')
        call dyn_debug_print(debugout_info, 'Finalizing MPAS dynamical core')
        ! Quick hack for dumping variables from MPAS dynamical core.
        ! Remove it once history and restart are wired up in CAM-SIMA.
        call dyn_variable_dump()
        ! After this point, do not access anything under MPAS dynamical core or runtime errors will ensue.
        call mpas_dynamical_core % final()
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine dyn_final
Call graph
dyn_final calls dyn_debug_print, dyn_variable_dump, dyn_final
dyn_debug_print calls dyn_debug_print, stringify
dyn_variable_dump calls check_allocate, endrun, get_variable_pointer, pio_closefile, pio_createfile, dyn_mpas_exchange_halo, dyn_mpas_read_write_stream, ps, shr_pio_getioformat, shr_pio_getiosys, shr_pio_getiotype
dyn_mpas_exchange_halo calls mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info, dyn_mpas_debug_print, stringify
dyn_mpas_read_write_stream calls dyn_mpas_exchange_halo, mpas_closestream, mpas_pool_destroy_pool, mpas_readstream, mpas_writestream, postread_reindex, postwrite_reindex, prewrite_reindex, dyn_mpas_debug_print, dyn_mpas_init_stream_with_pool, parse_stream_name
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_init_stream_with_pool calls mpas_pool_get_field, dyn_mpas_debug_print, parse_stream_name, stringify, mpas_createstream, mpas_pool_add_config, mpas_pool_create_pool, mpas_streamaddfield, add_stream_attribute, pio_file_is_open, dyn_mpas_check_variable_status
parse_stream_name calls tokenize, index_unique, parse_stream_name_fragment
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
dyn_mpas_check_variable_status calls mpas_pool_get_field, dyn_mpas_debug_print, stringify, pio_file_is_open, constituentnames, pio_inq_varid, pio_inq_varndims, pio_inq_vartype
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
tokenize_into_first_last calls split
tokenize_into_tokens_separator calls tokenize
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
stepon_final calls dyn_final