dyn_mpas_debug_print – MPAS Dynamical Core
dyn_mpas_debug_print Subroutine
Kuan-Chih Wang
2024-02-03
20 statements
Source File
private subroutine dyn_mpas_debug_print(self, level, message, printer)
Uses
dyn_mpas_procedures
This subroutine prints a debug message at a debug level. The debug message will be prefixed by "MPAS Subdriver (N): ", where N is the MPI rank. The debug level is one of the log_level_* constants. If printer is not supplied, the MPI root rank will print. Otherwise, the designated MPI rank will print instead.
Type Bound
mpas_dynamical_core_type
Arguments
Type Intent Optional Attributes Name
class(mpas_dynamical_core_type), intent(in) :: self
integer, intent(in) :: level
character(len=*), intent(in) :: message
integer, intent(in), optional :: printer
Calls
Called by
Source Code
    subroutine dyn_mpas_debug_print(self, level, message, printer)
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: stringify
        class(mpas_dynamical_core_type), intent(in) :: self
        integer, intent(in) :: level
        character(*), intent(in) :: message
        integer, optional, intent(in) :: printer
        ! Bail out early if the log level is less verbose than the debug level.
        if (self % log_level < level) then
            return
        end if
        if (present(printer)) then
            if (self % mpi_rank /= printer) then
                return
            end if
        else
            if (.not. self % mpi_rank_root) then
                return
            end if
        end if
        write(self % log_unit, '(a)') 'MPAS Subdriver (' // stringify([self % mpi_rank]) // '): ' // message
    end subroutine dyn_mpas_debug_print
Call graph
dyn_mpas_debug_print calls stringify
dyn_mpas_check_variable_status calls dyn_mpas_debug_print
dyn_mpas_compute_edge_wind calls dyn_mpas_debug_print, dyn_mpas_exchange_halo
dyn_mpas_compute_unit_vector calls dyn_mpas_debug_print
dyn_mpas_define_scalar calls dyn_mpas_debug_print
dyn_mpas_exchange_halo calls dyn_mpas_debug_print
dyn_mpas_final calls dyn_mpas_debug_print
dyn_mpas_get_global_mesh_dimension calls dyn_mpas_debug_print
dyn_mpas_get_local_mesh_dimension calls dyn_mpas_debug_print
dyn_mpas_init_phase1 calls dyn_mpas_debug_print
dyn_mpas_init_phase2 calls dyn_mpas_debug_print
dyn_mpas_init_phase3 calls dyn_mpas_debug_print
dyn_mpas_init_phase4 calls dyn_mpas_debug_print
dyn_mpas_init_stream_with_pool calls dyn_mpas_debug_print, dyn_mpas_check_variable_status, add_stream_attribute
dyn_mpas_read_namelist calls dyn_mpas_debug_print
dyn_mpas_read_write_stream calls dyn_mpas_debug_print, dyn_mpas_exchange_halo, dyn_mpas_init_stream_with_pool
dyn_mpas_run calls dyn_mpas_debug_print
dyn_exchange_constituent_states calls dyn_mpas_exchange_halo, dyn_exchange_constituent_states
dyn_init calls dyn_mpas_define_scalar, dyn_mpas_init_phase4, dyn_mpas_read_write_stream, dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
dyn_inquire_mesh_dimensions calls dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension, dyn_inquire_mesh_dimensions
dyn_readnl calls dyn_mpas_init_phase1, dyn_mpas_init_phase2, dyn_mpas_read_namelist, dyn_readnl
dyn_run calls dyn_mpas_run, dyn_run
dyn_variable_dump calls dyn_mpas_exchange_halo, dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_compute_unit_vector, dyn_mpas_init_phase3, dyn_mpas_read_write_stream, dyn_inquire_mesh_dimensions, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
physics_to_dynamics_coupling calls set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru, dyn_exchange_constituent_states, physics_to_dynamics_coupling
set_analytic_initial_condition calls set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u, set_mpas_state_w
dynamics_to_physics_coupling calls dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
stepon_run3 calls dyn_run
stepon_final calls dyn_final
stepon_run2 calls physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling