dynamics_to_physics_coupling – MPAS Dynamical Core
dynamics_to_physics_coupling Module Subroutine
230 statements
Source File
module subroutine dynamics_to_physics_coupling() Interface →
Uses
shr_kind_mod
dyn_comp
cam_logfile
dyn_grid
Perform one-way coupling from the dynamics output states to the physics input states. The other coupling direction is implemented by its counterpart, physics_to_dynamics_coupling. (KCW, 2024-07-31)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: column_index
real(kind=kind_r8), private, allocatable :: dp_col(:)
real(kind=kind_r8), private, allocatable :: dpd_col(:)
real(kind=kind_r8), private, allocatable :: dz_col(:)
real(kind=kind_dyn_mpas), private, pointer :: exner(:,:)
integer, private, pointer :: index_qv
integer, private, allocatable :: is_water_species_index(:)
real(kind=kind_r8), private, allocatable :: omega_mid_col(:)
real(kind=kind_r8), private, allocatable :: p_int_col(:)
real(kind=kind_r8), private, allocatable :: p_mid_col(:)
real(kind=kind_r8), private, allocatable :: pd_int_col(:)
real(kind=kind_r8), private, allocatable :: pd_mid_col(:)
real(kind=kind_r8), private, allocatable :: qv_mid_col(:)
real(kind=kind_r8), private, allocatable :: rho_mid_col(:)
real(kind=kind_dyn_mpas), private, pointer :: rho_zz(:,:)
real(kind=kind_r8), private, allocatable :: rhod_mid_col(:)
real(kind=kind_dyn_mpas), private, pointer :: scalars(:,:,:)
real(kind=kind_r8), private, allocatable :: sigma_all_q_mid_col(:)
character(len=*), private, parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling'
real(kind=kind_r8), private, allocatable :: t_mid_col(:)
real(kind=kind_dyn_mpas), private, pointer :: theta_m(:,:)
real(kind=kind_r8), private, allocatable :: tm_mid_col(:)
real(kind=kind_r8), private, allocatable :: tv_mid_col(:)
real(kind=kind_r8), private, allocatable :: u_mid_col(:)
real(kind=kind_dyn_mpas), private, pointer :: ucellmeridional(:,:)
real(kind=kind_dyn_mpas), private, pointer :: ucellzonal(:,:)
real(kind=kind_r8), private, allocatable :: v_mid_col(:)
real(kind=kind_dyn_mpas), private, pointer :: w(:,:)
real(kind=kind_r8), private, allocatable :: z_int_col(:)
real(kind=kind_dyn_mpas), private, pointer :: zgrid(:,:)
real(kind=kind_dyn_mpas), private, pointer :: zz(:,:)
Subroutines
subroutine final_shared_variables()
Finalize variables that are shared and repeatedly used by the update_shared_variables and set_physics_state_column internal subroutines. (KCW, 2024-07-20)
Arguments
None
subroutine init_shared_variables()
Initialize variables that are shared and repeatedly used by the update_shared_variables and set_physics_state_column internal subroutines. (KCW, 2024-07-20)
Arguments
None
subroutine set_physics_state_column(i)
Set variables for the specific column, indicated by i, in the physics_state derived type. This subroutine and update_shared_variables should be called in pairs. (KCW, 2024-07-30)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
subroutine set_physics_state_external()
Set variables in the physics_state derived type by calling external procedures. (KCW, 2024-07-30)
Arguments
None
subroutine update_shared_variables(i)
Update variables for the specific column, indicated by i. This subroutine and set_physics_state_column should be called in pairs. (KCW, 2024-07-30)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
Source Code
    module subroutine dynamics_to_physics_coupling()
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debugout_debug, debugout_info
        use dyn_comp, only: dyn_debug_print, kind_dyn_mpas
        use dyn_grid, only: ncells_solve
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: kind_r8 => shr_kind_r8
        character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling'
        integer :: column_index
        integer, allocatable :: is_water_species_index(:)
        integer, pointer :: index_qv
        ! Variable name suffixes have the following meanings:
        ! `*_col`: Variable is of each column.
        ! `*_int`: Variable is at layer interfaces.
        ! `*_mid`: Variable is at layer midpoints.
        real(kind_r8), allocatable :: pd_int_col(:), &       ! Dry hydrostatic air pressure (Pa).
                                      pd_mid_col(:), &       ! Dry non-hydrostatic air pressure (Pa).
                                      p_int_col(:), &        ! Full hydrostatic air pressure (Pa).
                                      p_mid_col(:), &        ! Full non-hydrostatic air pressure (Pa).
                                      z_int_col(:)           ! Geometric height (m).
        real(kind_r8), allocatable :: dpd_col(:), &          ! Dry air pressure difference (Pa) between layer interfaces.
                                      dp_col(:), &           ! Full air pressure difference (Pa) between layer interfaces.
                                      dz_col(:)              ! Geometric height difference (m) between layer interfaces.
        real(kind_r8), allocatable :: qv_mid_col(:), &       ! Water vapor mixing ratio (kg kg-1).
                                      sigma_all_q_mid_col(:) ! Summation of all water species mixing ratios (kg kg-1).
        real(kind_r8), allocatable :: rhod_mid_col(:), &     ! Dry air density (kg m-3).
                                      rho_mid_col(:)         ! Full air density (kg m-3).
        real(kind_r8), allocatable :: t_mid_col(:), &        ! Temperature (K).
                                      tm_mid_col(:), &       ! Modified "moist" temperature (K).
                                      tv_mid_col(:)          ! Virtual temperature (K).
        real(kind_r8), allocatable :: u_mid_col(:), &        ! Eastward wind velocity (m s-1).
                                      v_mid_col(:), &        ! Northward wind velocity (m s-1).
                                      omega_mid_col(:)       ! Vertical pressure velocity (Pa s-1).
        real(kind_dyn_mpas), pointer :: exner(:, :)
        real(kind_dyn_mpas), pointer :: rho_zz(:, :)
        real(kind_dyn_mpas), pointer :: scalars(:, :, :)
        real(kind_dyn_mpas), pointer :: theta_m(:, :)
        real(kind_dyn_mpas), pointer :: ucellzonal(:, :), ucellmeridional(:, :), w(:, :)
        real(kind_dyn_mpas), pointer :: zgrid(:, :)
        real(kind_dyn_mpas), pointer :: zz(:, :)
        call dyn_debug_print(debugout_debug, subname // ' entered')
        call init_shared_variables()
        call dyn_exchange_constituent_states(direction='i', exchange=.true., conversion=.false.)
        call dyn_debug_print(debugout_info, 'Setting physics state variables column by column')
        ! Set variables in the `physics_state` derived type column by column.
        ! This way, peak memory usage can be reduced.
        do column_index = 1, ncells_solve
            call update_shared_variables(column_index)
            call set_physics_state_column(column_index)
        end do
        call set_physics_state_external()
        call final_shared_variables()
        call dyn_debug_print(debugout_debug, subname // ' completed')
    contains
        !> Initialize variables that are shared and repeatedly used by the `update_shared_variables` and
        !> `set_physics_state_column` internal subroutines.
        !> (KCW, 2024-07-20)
        subroutine init_shared_variables()
            ! Module(s) from CAM-SIMA.
            use cam_abortutils, only: check_allocate
            use cam_constituents, only: const_is_water_species, &
                                        num_advected
            use dyn_comp, only: advected_constituent_index, mpas_dynamical_core
            use vert_coord, only: pver, pverp
            ! Module(s) from CESM Share.
            use shr_kind_mod, only: len_cx => shr_kind_cx
            character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling::init_shared_variables'
            character(len_cx) :: cerr
            integer :: i
            integer :: ierr
            logical, allocatable :: is_water_species(:)
            call dyn_debug_print(debugout_info, 'Preparing for dynamics-physics coupling')
            nullify(index_qv)
            nullify(exner)
            nullify(rho_zz)
            nullify(scalars)
            nullify(theta_m)
            nullify(ucellzonal, ucellmeridional, w)
            nullify(zgrid)
            nullify(zz)
            allocate(is_water_species(num_advected), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'is_water_species(num_advected)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            do i = 1, num_advected
                is_water_species(i) = const_is_water_species(advected_constituent_index(i))
            end do
            allocate(is_water_species_index(count(is_water_species)), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'is_water_species_index(count(is_water_species))', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            is_water_species_index(:) = &
                pack([(mpas_dynamical_core % map_mpas_scalar_index(i), i = 1, num_advected)], is_water_species)
            deallocate(is_water_species)
            allocate(pd_int_col(pverp), pd_mid_col(pver), p_int_col(pverp), p_mid_col(pver), z_int_col(pverp), &
                errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'pd_int_col(pverp), pd_mid_col(pver), p_int_col(pverp), p_mid_col(pver), z_int_col(pverp)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(dpd_col(pver), dp_col(pver), dz_col(pver), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'dpd_col(pver), dp_col(pver), dz_col(pver)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(qv_mid_col(pver), sigma_all_q_mid_col(pver), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'qv_mid_col(pver), sigma_all_q_mid_col(pver)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(rhod_mid_col(pver), rho_mid_col(pver), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'rhod_mid_col(pver), rho_mid_col(pver)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(t_mid_col(pver), tm_mid_col(pver), tv_mid_col(pver), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                't_mid_col(pver), tm_mid_col(pver), tv_mid_col(pver)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            allocate(u_mid_col(pver), v_mid_col(pver), omega_mid_col(pver), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'u_mid_col(pver), v_mid_col(pver), omega_mid_col(pver)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            call mpas_dynamical_core % get_variable_pointer(index_qv, 'dim', 'index_qv')
            call mpas_dynamical_core % get_variable_pointer(exner, 'diag', 'exner')
            call mpas_dynamical_core % get_variable_pointer(rho_zz, 'state', 'rho_zz', time_level=1)
            call mpas_dynamical_core % get_variable_pointer(scalars, 'state', 'scalars', time_level=1)
            call mpas_dynamical_core % get_variable_pointer(theta_m, 'state', 'theta_m', time_level=1)
            call mpas_dynamical_core % get_variable_pointer(ucellzonal, 'diag', 'uReconstructZonal')
            call mpas_dynamical_core % get_variable_pointer(ucellmeridional, 'diag', 'uReconstructMeridional')
            call mpas_dynamical_core % get_variable_pointer(w, 'state', 'w', time_level=1)
            call mpas_dynamical_core % get_variable_pointer(zgrid, 'mesh', 'zgrid')
            call mpas_dynamical_core % get_variable_pointer(zz, 'mesh', 'zz')
        end subroutine init_shared_variables
        !> Finalize variables that are shared and repeatedly used by the `update_shared_variables` and
        !> `set_physics_state_column` internal subroutines.
        !> (KCW, 2024-07-20)
        subroutine final_shared_variables()
            character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling::final_shared_variables'
            deallocate(is_water_species_index)
            deallocate(pd_int_col, pd_mid_col, p_int_col, p_mid_col, z_int_col)
            deallocate(dpd_col, dp_col, dz_col)
            deallocate(qv_mid_col, sigma_all_q_mid_col)
            deallocate(rhod_mid_col, rho_mid_col)
            deallocate(t_mid_col, tm_mid_col, tv_mid_col)
            deallocate(u_mid_col, v_mid_col, omega_mid_col)
            nullify(index_qv)
            nullify(exner)
            nullify(rho_zz)
            nullify(scalars)
            nullify(theta_m)
            nullify(ucellzonal, ucellmeridional, w)
            nullify(zgrid)
            nullify(zz)
        end subroutine final_shared_variables
        !> Update variables for the specific column, indicated by `i`. This subroutine and `set_physics_state_column`
        !> should be called in pairs.
        !> (KCW, 2024-07-30)
        subroutine update_shared_variables(i)
            ! Module(s) from CAM-SIMA.
            use dyn_procedures, only: dp_by_hydrostatic_equation, omega_of_w_rho, p_by_equation_of_state, t_of_tm_qv
            use dynconst, only: constant_g => gravit, constant_rd => rair, constant_rv => rh2o
            use vert_coord, only: pver, pverp
            ! Module(s) from MPAS.
            use dyn_mpas_procedures, only: clamp
            integer, intent(in) :: i
            character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling::update_shared_variables'
            integer :: k
            ! Proximity limit, in fraction, on how close `p{,d}_mid_col` is allowed to be around its surrounding `p{,d}_int_col`.
            real(kind_r8), parameter :: p_int_mid_proximity_limit = 0.05_kind_r8
            ! The summation term of equation 5 in doi:10.1029/2017MS001257.
            sigma_all_q_mid_col(:) = 1.0_kind_r8 + sum(real(scalars(is_water_species_index, :, i), kind_r8), 1)
            ! Compute thermodynamic variables.
            ! By definition.
            z_int_col(:) = real(zgrid(:, i), kind_r8)
            dz_col(:) = z_int_col(2:pverp) - z_int_col(1:pver)
            qv_mid_col(:) = real(scalars(index_qv, :, i), kind_r8)
            rhod_mid_col(:) = real(rho_zz(:, i) * zz(:, i), kind_r8)
            ! Equation 5 in doi:10.1029/2017MS001257.
            rho_mid_col(:) = rhod_mid_col(:) * sigma_all_q_mid_col(:)
            ! Hydrostatic equation.
            dpd_col(:) = dp_by_hydrostatic_equation(constant_g, rhod_mid_col, dz_col)
            dp_col(:) = dp_by_hydrostatic_equation(constant_g, rho_mid_col, dz_col)
            ! By definition of Exner function. Also see below.
            tm_mid_col(:) = real(theta_m(:, i) * exner(:, i), kind_r8)
            ! The paragraph below equation 2.7 in doi:10.5065/1DFH-6P97.
            ! The paragraph below equation 2 in doi:10.1175/MWR-D-11-00215.1.
            t_mid_col(:) = t_of_tm_qv(constant_rd, constant_rv, tm_mid_col, qv_mid_col)
            ! Equation 16 in doi:10.1029/2017MS001257.
            ! The numerator terms are just `tm_mid_col` here (i.e., modified "moist" temperature).
            tv_mid_col(:) = tm_mid_col(:) / sigma_all_q_mid_col(:)
            ! Equation of state.
            ! Equation 11 in doi:10.1029/2017MS001257.
            pd_mid_col(:) = p_by_equation_of_state(constant_rd, rhod_mid_col, t_mid_col)
            ! Equation 17 in doi:10.1029/2017MS001257.
            p_mid_col(:) = p_by_equation_of_state(constant_rd, rho_mid_col, tv_mid_col)
            ! By definition.
            pd_int_col(pverp) = pd_mid_col(pver) + 0.5_kind_r8 * dpd_col(pver)
            p_int_col(pverp) = p_mid_col(pver) + 0.5_kind_r8 * dp_col(pver)
            ! Integrate downward.
            do k = pver, 1, -1
                pd_int_col(k) = pd_int_col(k + 1) - dpd_col(k)
                p_int_col(k) = p_int_col(k + 1) - dp_col(k)
            end do
            ! `p{,d}_mid_col` is not guaranteed to be bounded by `p{,d}_int_col` because the former is non-hydrostatic
            ! while the latter is hydrostatic. In high-resolution simulations, the former could exceed the latter,
            ! leading to a model crash in physics.
            ! Impose range limits on `p{,d}_mid_col` so it is bounded by `p{,d}_int_col`.
            pd_mid_col(:) = clamp( &
                pd_mid_col, &
                pd_int_col(2:pverp) - dpd_col(:) * p_int_mid_proximity_limit, &
                pd_int_col(1:pver) + dpd_col(:) * p_int_mid_proximity_limit)
            p_mid_col(:) = clamp( &
                p_mid_col, &
                p_int_col(2:pverp) - dp_col(:) * p_int_mid_proximity_limit, &
                p_int_col(1:pver) + dp_col(:) * p_int_mid_proximity_limit)
            ! Compute momentum variables.
            ! By definition.
            u_mid_col(:) = real(ucellzonal(:, i), kind_r8)
            v_mid_col(:) = real(ucellmeridional(:, i), kind_r8)
            omega_mid_col(:) = omega_of_w_rho(constant_g, 0.5_kind_r8 * real(w(1:pver, i) + w(2:pverp, i), kind_r8), rhod_mid_col)
        end subroutine update_shared_variables
        !> Set variables for the specific column, indicated by `i`, in the `physics_state` derived type.
        !> This subroutine and `update_shared_variables` should be called in pairs.
        !> (KCW, 2024-07-30)
        subroutine set_physics_state_column(i)
            ! Module(s) from CAM-SIMA.
            use dyn_procedures, only: reverse
            use dynconst, only: constant_g => gravit
            use physics_types, only: phys_state
            integer, intent(in) :: i
            character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling::set_physics_state_column'
            ! Vertical index order is reversed between CAM-SIMA and MPAS.
            ! Always call `reverse` when assigning anything to/from the `physics_state` derived type.
            phys_state % u(i, :) = reverse(u_mid_col)
            phys_state % v(i, :) = reverse(v_mid_col)
            phys_state % omega(i, :) = reverse(omega_mid_col)
            phys_state % psdry(i) = pd_int_col(1)
            phys_state % pintdry(i, :) = reverse(pd_int_col)
            phys_state % pmiddry(i, :) = reverse(pd_mid_col)
            phys_state % pdeldry(i, :) = reverse(-dpd_col)
            phys_state % lnpintdry(i, :) = log(phys_state % pintdry(i, :))
            phys_state % lnpmiddry(i, :) = log(phys_state % pmiddry(i, :))
            phys_state % rpdeldry(i, :) = 1.0_kind_r8 / phys_state % pdeldry(i, :)
            phys_state % ps(i) = p_int_col(1)
            phys_state % pint(i, :) = reverse(p_int_col)
            phys_state % pmid(i, :) = reverse(p_mid_col)
            phys_state % pdel(i, :) = reverse(-dp_col)
            phys_state % lnpint(i, :) = log(phys_state % pint(i, :))
            phys_state % lnpmid(i, :) = log(phys_state % pmid(i, :))
            phys_state % rpdel(i, :) = 1.0_kind_r8 / phys_state % pdel(i, :)
            phys_state % t(i, :) = reverse(t_mid_col)
            phys_state % phis(i) = constant_g * z_int_col(1)
        end subroutine set_physics_state_column
        !> Set variables in the `physics_state` derived type by calling external procedures.
        !> (KCW, 2024-07-30)
        subroutine set_physics_state_external()
            ! Module(s) from CAM-SIMA.
            use cam_abortutils, only: check_allocate, endrun
            use cam_constituents, only: const_qmin, &
                                        num_constituents
            use cam_thermo, only: cam_thermo_dry_air_update, cam_thermo_water_update
            use cam_thermo_formula, only: energy_formula_dycore_mpas
            use dyn_comp, only: advected_constituent_index, mpas_dynamical_core
            use dyn_procedures, only: exner_function
            use dynconst, only: constant_g => gravit
            use physics_types, only: cappav, cp_or_cv_dycore, cpairv, lagrangian_vertical, phys_state, rairv, zvirv
            use runtime_obj, only: cam_runtime_opts
            use string_utils, only: stringify
            use vert_coord, only: pver, pverp
            ! Module(s) from CCPP.
            use cam_ccpp_cap, only: cam_constituents_array, cam_model_const_properties
            use ccpp_constituent_prop_mod, only: ccpp_constituent_prop_ptr_t
            use ccpp_kinds, only: kind_phys
            use geopotential_temp, only: geopotential_temp_run
            use qneg, only: qneg_run
            use static_energy, only: update_dry_static_energy_run
            ! Module(s) from CESM Share.
            use shr_kind_mod, only: len_cx => shr_kind_cx
            character(*), parameter :: subname = 'dyn_coupling::dynamics_to_physics_coupling::set_physics_state_external'
            character(len_cx) :: cerr
            integer :: i
            integer :: ierr
            real(kind_phys), allocatable :: minimum_constituents(:)
            real(kind_phys), pointer :: constituents(:, :, :)
            type(ccpp_constituent_prop_ptr_t), pointer :: constituent_properties(:)
            call dyn_debug_print(debugout_info, 'Setting physics state variables externally')
            nullify(constituents)
            nullify(constituent_properties)
            allocate(minimum_constituents(num_constituents), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, &
                'minimum_constituents(num_constituents)', &
                file='dyn_coupling', line=__LINE__, errmsg=trim(adjustl(cerr)))
            do i = 1, num_constituents
                minimum_constituents(i) = const_qmin(i)
            end do
            constituents => cam_constituents_array()
            if (.not. associated(constituents)) then
                call endrun('Failed to find variable "constituents"', subname, __LINE__)
            end if
            constituent_properties => cam_model_const_properties()
            if (.not. associated(constituent_properties)) then
                call endrun('Failed to find variable "constituent_properties"', subname, __LINE__)
            end if
            ! Update `cappav`, `cpairv`, `rairv`, `zvirv`, etc. as needed by calling `cam_thermo_dry_air_update`.
            ! Note that this subroutine expects constituents to be dry.
            call cam_thermo_dry_air_update( &
                constituents, phys_state % t, ncells_solve, pver, cam_runtime_opts % update_thermodynamic_variables())
            ! Update `cp_or_cv_dycore` by calling `cam_thermo_water_update`.
            ! Note that this subroutine expects constituents to be dry.
            call cam_thermo_water_update( &
                constituents, ncells_solve, pver, energy_formula_dycore_mpas, cp_or_cv_dycore)
            ! This variable name is really misleading. It actually represents the reciprocal of Exner function
            ! with respect to surface pressure. This definition is sometimes used for boundary layer work. See
            ! the paragraph below equation 1.5.1c in doi:10.1007/978-94-009-3027-8.
            ! Also note that `cappav` is updated externally by `cam_thermo_dry_air_update`.
            do i = 1, ncells_solve
                phys_state % exner(i, :) = 1.0_kind_r8 / exner_function(cappav(i, :), phys_state % ps(i), phys_state % pmid(i, :))
            end do
            ! Note that constituents become moist after this.
            call dyn_exchange_constituent_states(direction='i', exchange=.false., conversion=.true.)
            ! Impose minimum limits on constituents.
            call qneg_run(subname, ncells_solve, pver, minimum_constituents, constituents, ierr, cerr)
            if (ierr /= 0) then
                call endrun('Failed to impose minimum limits on constituents externally' // new_line('') // &
                    'External procedure returned with ' // stringify([ierr]) // ': ' // trim(adjustl(cerr)), &
                    subname, __LINE__)
            end if
            ! The `mpas_dynamical_core % map_constituent_index` type-bound function maps MPAS scalar index to
            ! CAM-SIMA *advected* constituent index. Then, the `advected_constituent_index` lookup table maps
            ! *advected* constituent index to *all* constituent index.
            i = advected_constituent_index(mpas_dynamical_core % map_constituent_index(index_qv))
            ! Set `zi` (i.e., geopotential height at layer interfaces) and `zm` (i.e., geopotential height at layer midpoints).
            ! Note that `rairv` and `zvirv` are updated externally by `cam_thermo_dry_air_update`.
            call geopotential_temp_run( &
                pver, lagrangian_vertical, pver, 1, pverp, 1, num_constituents, &
                phys_state % lnpint, phys_state % pint, phys_state % pmid, phys_state % pdel, phys_state % rpdel, phys_state % t, &
                constituents(:, :, i), constituents, constituent_properties, &
                rairv, constant_g, zvirv, phys_state % zi, phys_state % zm, ncells_solve, ierr, cerr)
            if (ierr /= 0) then
                call endrun('Failed to set variable "zi" and "zm" externally' // new_line('') // &
                    'External procedure returned with ' // stringify([ierr]) // ': ' // trim(adjustl(cerr)), &
                    subname, __LINE__)
            end if
            ! Set `dse` (i.e., dry static energy).
            ! Note that `cpairv` is updated externally by `cam_thermo_dry_air_update`.
            call update_dry_static_energy_run( &
                pver, constant_g, phys_state % t, phys_state % zm, phys_state % phis, phys_state % dse, cpairv, ierr, cerr)
            if (ierr /= 0) then
                call endrun('Failed to set variable "dse" externally' // new_line('') // &
                    'External procedure returned with ' // stringify([ierr]) // ': ' // trim(adjustl(cerr)), &
                    subname, __LINE__)
            end if
            deallocate(minimum_constituents)
            nullify(constituents)
            nullify(constituent_properties)
        end subroutine set_physics_state_external
    end subroutine dynamics_to_physics_coupling
Call graph
dynamics_to_physics_coupling calls dyn_debug_print, dyn_exchange_constituent_states, final_shared_variables, init_shared_variables, set_physics_state_column, set_physics_state_external, update_shared_variables, dynamics_to_physics_coupling
dyn_debug_print calls dyn_debug_print, stringify
dyn_exchange_constituent_states calls dyn_exchange_constituent_states, dyn_debug_print, check_allocate, const_is_water_species, endrun, reverse, get_variable_pointer, pdel, pdeldry, dyn_mpas_map_constituent_index, dyn_mpas_map_mpas_scalar_index, cam_advected_constituents_array, const_is_dry, dyn_mpas_exchange_halo
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
exner_function calls exner_function_of_cpd_p0_rd_p, exner_function_of_kappa_p0_p
reverse calls reverse_real32, reverse_real64
dyn_mpas_exchange_halo calls mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info, dyn_mpas_debug_print, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_debug_print calls stringify
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
stepon_timestep_init calls dynamics_to_physics_coupling