dzw_of_rdzw_real32 – MPAS Dynamical Core
dzw_of_rdzw_real32 Function
6 statements
Source File
private pure elemental function dzw_of_rdzw_real32(rdzw) result(dzw)
Uses
iso_fortran_env
Compute the differences in between w-wind levels dzw from the reciprocal differences in between w-wind levels rdzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: rdzw
Return Value real(kind=real32)
Called by
Source Code
    pure elemental function dzw_of_rdzw_real32(rdzw) result(dzw)
        use, intrinsic :: iso_fortran_env, only: real32
        real(real32), intent(in) :: rdzw
        real(real32) :: dzw
        dzw = 1.0_real32 / rdzw
    end function dzw_of_rdzw_real32
Call graph
dzw_of_rdzw calls dzw_of_rdzw_real32
init_reference_pressure calls dzw_of_rdzw
model_grid_init calls init_reference_pressure, model_grid_init