exner_function_of_kappa_p0_p – MPAS Dynamical Core
exner_function_of_kappa_p0_p Function
6 statements
Source File
private pure elemental function exner_function_of_kappa_p0_p(constant_kappa, constant_p0, p) result(pi)
Uses
iso_fortran_env
Compute the Exner function pi from the pressure p. Essentially, .
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_kappa
real(kind=real64), intent(in) :: constant_p0
real(kind=real64), intent(in) :: p
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function exner_function_of_kappa_p0_p(constant_kappa, constant_p0, p) result(pi)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_kappa, constant_p0, p
        real(real64) :: pi
        pi = (p / constant_p0) ** constant_kappa
    end function exner_function_of_kappa_p0_p
Call graph
exner_function calls exner_function_of_kappa_p0_p
dynamics_to_physics_coupling calls set_physics_state_external, dynamics_to_physics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling