init_physics_grid – MPAS Dynamical Core
init_physics_grid Subroutine
60 statements
Source File
subroutine init_physics_grid()
Uses
shr_kind_mod
dyn_comp
dynconst
string_utils
cam_abortutils
physics_grid
cam_logfile
spmd_utils
physics_column_type
Initialize physics grid in terms of dynamics decomposition. Provide grid and mapping information between global and local indexes to physics by calling phys_grid_init. (KCW, 2024-03-27)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=kind_dyn_mpas), private, pointer :: areacell(:)
character(len=len_cx), private :: cerr
character(len=max_hcoordname_len), private, allocatable :: dyn_attribute_name(:)
type(physics_column_t), private, allocatable :: dyn_column(:)
integer, private :: hdim1_d
integer, private :: hdim2_d
integer, private :: i
integer, private :: ierr
integer, private, pointer :: indextocellid(:)
real(kind=kind_dyn_mpas), private, pointer :: latcell(:)
real(kind=kind_dyn_mpas), private, pointer :: loncell(:)
character(len=*), private, parameter :: subname = 'dyn_grid::init_physics_grid'
Source Code
    subroutine init_physics_grid()
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: check_allocate
        use cam_logfile, only: debugout_debug
        use dyn_comp, only: dyn_debug_print, mpas_dynamical_core
        use dynconst, only: constant_pi => pi, rad_to_deg
        use physics_column_type, only: kind_pcol, physics_column_t
        use physics_grid, only: phys_grid_init
        use spmd_utils, only: iam
        use string_utils, only: stringify
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: kind_r8 => shr_kind_r8, &
                                len_cx => shr_kind_cx
        character(*), parameter :: subname = 'dyn_grid::init_physics_grid'
        character(len_cx) :: cerr
        character(max_hcoordname_len), allocatable :: dyn_attribute_name(:)
        integer :: hdim1_d, hdim2_d ! First and second horizontal dimensions of physics grid.
        integer :: i
        integer :: ierr
        integer, pointer :: indextocellid(:)        ! Global indexes of cell centers.
        real(kind_dyn_mpas), pointer :: areacell(:) ! Cell areas (m2).
        real(kind_dyn_mpas), pointer :: latcell(:)  ! Cell center latitudes (rad).
        real(kind_dyn_mpas), pointer :: loncell(:)  ! Cell center longitudes (rad).
        type(physics_column_t), allocatable :: dyn_column(:) ! Grid and mapping information between global and local indexes.
        call dyn_debug_print(debugout_debug, subname // ' entered')
        nullify(areacell)
        nullify(indextocellid)
        nullify(latcell)
        nullify(loncell)
        hdim1_d = ncells_global
        ! Setting `hdim2_d` to `1` indicates unstructured grid.
        hdim2_d = 1
        call mpas_dynamical_core % get_variable_pointer(areacell, 'mesh', 'areaCell')
        call mpas_dynamical_core % get_variable_pointer(indextocellid, 'mesh', 'indexToCellID')
        call mpas_dynamical_core % get_variable_pointer(latcell, 'mesh', 'latCell')
        call mpas_dynamical_core % get_variable_pointer(loncell, 'mesh', 'lonCell')
        allocate(dyn_column(ncells_solve), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'dyn_column(ncells_solve)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        do i = 1, ncells_solve
            ! Column information.
            dyn_column(i) % lat_rad = real(latcell(i), kind_pcol)
            dyn_column(i) % lon_rad = real(loncell(i), kind_pcol)
            dyn_column(i) % lat_deg = real(real(latcell(i), kind_r8) * rad_to_deg, kind_pcol)
            dyn_column(i) % lon_deg = real(real(loncell(i), kind_r8) * rad_to_deg, kind_pcol)
            ! Cell areas normalized to unit sphere.
            dyn_column(i) % area    = real(areacell(i) / (sphere_radius ** 2), kind_pcol)
            ! Cell weights normalized to unity.
            dyn_column(i) % weight  = &
                real(real(areacell(i), kind_r8) / (4.0_kind_r8 * constant_pi * real(sphere_radius, kind_r8) ** 2), kind_pcol)
            ! File decomposition.
            ! For unstructured grid, `coord_indices` is not used by `phys_grid_init`.
            dyn_column(i) % coord_indices(:) = -1
            ! In this case, `global_col_num` is used instead.
            dyn_column(i) % global_col_num   = indextocellid(i)
            ! Dynamics decomposition.
            dyn_column(i) % dyn_task         = iam
            dyn_column(i) % global_dyn_block = indextocellid(i)
            dyn_column(i) % local_dyn_block  = i
            ! `dyn_block_index` is not used due to no dynamics block offset, but it still needs to be allocated.
            allocate(dyn_column(i) % dyn_block_index(0), errmsg=cerr, stat=ierr)
            call check_allocate(ierr, subname, 'dyn_column(' // stringify([i]) // ') % dyn_block_index(0)', &
                file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        end do
        nullify(areacell)
        nullify(indextocellid)
        nullify(latcell)
        nullify(loncell)
        ! `phys_grid_init` expects to receive the `area` attribute from dynamics.
        ! However, do not let it because dynamics grid is different from physics grid.
        allocate(dyn_attribute_name(0), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'dyn_attribute_name(0)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        call phys_grid_init(hdim1_d, hdim2_d, 'mpas', dyn_column, 'mpas_cell', dyn_attribute_name)
        deallocate(dyn_column)
        deallocate(dyn_attribute_name)
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine init_physics_grid
Call graph
init_physics_grid calls check_allocate, coord_indices, dyn_block_index, dyn_debug_print, get_variable_pointer, phys_grid_init, stringify
dyn_debug_print calls dyn_debug_print, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
model_grid_init calls init_physics_grid, model_grid_init