init_reference_pressure – MPAS Dynamical Core
init_reference_pressure Subroutine
65 statements
Source File
subroutine init_reference_pressure()
Uses
shr_kind_mod
dyn_mpas_procedures
string_utils
std_atm_profile
cam_logfile
dyn_procedures
dyn_comp
vert_coord
dynconst
ref_pres
cam_history_support
cam_abortutils
Initialize reference pressure for use by physics. (KCW, 2024-03-25)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=len_cx), private :: cerr
real(kind=kind_r8), private, allocatable :: dzw(:)
integer, private :: ierr
integer, private :: k
integer, private :: l
integer, private, parameter :: num_pure_p_lev = 0
real(kind=kind_r8), private, allocatable :: p_ref_int(:)
real(kind=kind_r8), private, allocatable :: p_ref_mid(:)
real(kind=kind_dyn_mpas), private, pointer :: rdzw(:)
character(len=*), private, parameter :: subname = 'dyn_grid::init_reference_pressure'
real(kind=kind_r8), private, pointer :: zu(:)
real(kind=kind_r8), private, pointer :: zw(:)
Source Code
    subroutine init_reference_pressure()
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: check_allocate
        use cam_history_support, only: add_vert_coord
        use cam_logfile, only: debugout_debug, debugout_verbose
        use dyn_comp, only: dyn_debug_print, mpas_dynamical_core
        use dyn_procedures, only: reverse
        use dynconst, only: constant_p0 => pref
        use ref_pres, only: ref_pres_init
        use std_atm_profile, only: std_atm_pres
        use string_utils, only: stringify
        use vert_coord, only: pver, pverp
        ! Module(s) from CESM Share.
        use shr_kind_mod, only: kind_r8 => shr_kind_r8, &
                                len_cx => shr_kind_cx
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: dzw_of_rdzw, zu_of_dzw, zw_of_dzw
        character(*), parameter :: subname = 'dyn_grid::init_reference_pressure'
        character(len_cx) :: cerr
        ! Number of pure pressure levels at model top.
        integer, parameter :: num_pure_p_lev = 0
        integer :: ierr
        integer :: k, l
        ! Reference pressure (Pa) at layer interfaces and midpoints.
        real(kind_r8), allocatable :: p_ref_int(:)
        real(kind_r8), allocatable :: p_ref_mid(:)
        ! In MPAS, the vertical coordinate is denoted as lowercase "zeta", a Greek alphabet.
        ! `zu` denotes zeta at u-wind levels (i.e., at layer midpoints).
        ! `zw` denotes zeta at w-wind levels (i.e., at layer interfaces).
        ! `dzw` denotes the delta/difference between `zw`.
        ! `rdzw` denotes the reciprocal of `dzw`.
        real(kind_r8), allocatable :: dzw(:)
        real(kind_dyn_mpas), pointer :: rdzw(:)
        real(kind_r8), pointer :: zu(:) ! CANNOT be safely deallocated because `add_vert_coord`
                                        ! just uses pointers to point at it internally.
        real(kind_r8), pointer :: zw(:) ! CANNOT be safely deallocated because `add_vert_coord`
                                        ! just uses pointers to point at it internally.
        call dyn_debug_print(debugout_debug, subname // ' entered')
        nullify(rdzw)
        nullify(zu)
        nullify(zw)
        ! Compute reference height.
        call mpas_dynamical_core % get_variable_pointer(rdzw, 'mesh', 'rdzw')
        allocate(dzw(pver), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'dzw(pver)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        dzw(:) = dzw_of_rdzw(real(rdzw, kind_r8))
        nullify(rdzw)
        allocate(zw(pverp), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'zw(pverp)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        allocate(zu(pver), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'zu(pver)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        ! In MPAS, zeta coordinates are stored in increasing order (i.e., bottom to top of atmosphere).
        ! In CAM-SIMA, however, index order is reversed (i.e., top to bottom of atmosphere).
        zw(:) = reverse(zw_of_dzw(dzw))
        zu(:) = reverse(zu_of_dzw(dzw))
        deallocate(dzw)
        ! Register zeta coordinates with history.
        call add_vert_coord('ilev', pverp, 'Height (zeta) level at layer interfaces', 'm', zw, &
            positive='up')
        call add_vert_coord('lev', pver, 'Height (zeta) level at layer midpoints', 'm', zu, &
            positive='up')
        ! Compute reference pressure from reference height.
        allocate(p_ref_int(pverp), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'p_ref_int(pverp)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        call std_atm_pres(zw, p_ref_int, user_specified_ps=constant_p0)
        allocate(p_ref_mid(pver), errmsg=cerr, stat=ierr)
        call check_allocate(ierr, subname, 'p_ref_mid(pver)', &
            file='dyn_grid', line=__LINE__, errmsg=trim(adjustl(cerr)))
        p_ref_mid(:) = 0.5_kind_r8 * (p_ref_int(1:pver) + p_ref_int(2:pverp))
        ! Print a nice table of reference height and pressure.
        call dyn_debug_print(debugout_verbose, 'Reference layer information:')
        call dyn_debug_print(debugout_verbose, '----- | -------------- | --------------')
        call dyn_debug_print(debugout_verbose, 'Index |     Height (m) | Pressure (hPa)')
        do k = 1, pver
            call dyn_debug_print(debugout_verbose, repeat('-', 5) // ' |  ' // stringify([zw(k)]) // &
                ' |  ' // stringify([p_ref_int(k) / 100.0_kind_r8]))
            l = len(stringify([k]))
            call dyn_debug_print(debugout_verbose, repeat(' ', 5 - l) // stringify([k]) // ' |  ' // stringify([zu(k)]) // &
                ' |  ' // stringify([p_ref_mid(k) / 100.0_kind_r8]))
        end do
        k = pverp
        call dyn_debug_print(debugout_verbose, repeat('-', 5) // ' |  ' // stringify([zw(k)]) // &
            ' |  ' // stringify([p_ref_int(k) / 100.0_kind_r8]))
        call ref_pres_init(p_ref_int, p_ref_mid, num_pure_p_lev)
        deallocate(p_ref_int)
        deallocate(p_ref_mid)
        nullify(zu)
        nullify(zw)
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine init_reference_pressure
Call graph
init_reference_pressure calls add_vert_coord, check_allocate, dyn_debug_print, dzw_of_rdzw, reverse, zu_of_dzw, zw_of_dzw, get_variable_pointer, ref_pres_init, std_atm_pres, stringify
dyn_debug_print calls dyn_debug_print, stringify
dzw_of_rdzw calls dzw_of_rdzw_real32, dzw_of_rdzw_real64
reverse calls reverse_real32, reverse_real64
zu_of_dzw calls zu_of_dzw_real32, zu_of_dzw_real64
zw_of_dzw calls zw_of_dzw_real32, zw_of_dzw_real64
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
zu_of_dzw_real32 calls zw_of_dzw
zu_of_dzw_real64 calls zw_of_dzw
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
model_grid_init calls init_reference_pressure, model_grid_init