model_grid_init – MPAS Dynamical Core
model_grid_init Module Subroutine
39 statements
Source File
module subroutine model_grid_init() Interface →
Uses
cam_initfiles
string_utils
pio
cam_logfile
cam_constituents
dyn_comp
vert_coord
dynconst
cam_abortutils
Initialize various model grids (e.g., dynamics, physics) in terms of dynamics decomposition. Additionally, MPAS framework initialization and reading time-invariant (e.g., grid/mesh) variables are also being completed in this subroutine. (KCW, 2024-03-29)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(file_desc_t), private, pointer :: pio_file
character(len=*), private, parameter :: subname = 'dyn_grid::model_grid_init'
Source Code
    module subroutine model_grid_init()
        ! Module(s) from CAM-SIMA.
        use cam_abortutils, only: endrun
        use cam_constituents, only: num_advected
        use cam_initfiles, only: initial_file_get_id
        use cam_logfile, only: debugout_debug, debugout_info, debugout_verbose
        use dyn_comp, only: dyn_debug_print, mpas_dynamical_core
        use dynconst, only: dynconst_init
        use string_utils, only: stringify
        use vert_coord, only: pver, vert_coord_init
        ! Module(s) from external libraries.
        use pio, only: file_desc_t
        character(*), parameter :: subname = 'dyn_grid::model_grid_init'
        type(file_desc_t), pointer :: pio_file
        call dyn_debug_print(debugout_debug, subname // ' entered')
        nullify(pio_file)
        ! Initialize mathematical and physical constants for dynamics.
        call dynconst_init()
        call dyn_debug_print(debugout_info, 'Initializing vertical coordinate indexes')
        ! Initialize vertical coordinate indexes.
        ! `pver` comes from CAM-SIMA namelist.
        ! `pverp` is set only after this call. Call it as soon as possible.
        call vert_coord_init(1, pver)
        ! Get PIO file descriptor for initial file.
        pio_file => initial_file_get_id()
        call dyn_debug_print(debugout_info, 'Initializing MPAS dynamical core (Phase 3/4)')
        ! Finish MPAS framework initialization, including
        ! the allocation of all blocks and fields managed by MPAS.
        call mpas_dynamical_core % init_phase3(num_advected, pio_file)
        call dyn_debug_print(debugout_info, 'Initializing MPAS mesh variables')
        ! Read time-invariant (e.g., grid/mesh) variables.
        call mpas_dynamical_core % read_write_stream(pio_file, 'r', 'invariant')
        nullify(pio_file)
        ! Compute local east, north and edge-normal unit vectors whenever time-invariant (e.g., grid/mesh) variables are read.
        call mpas_dynamical_core % compute_unit_vector()
        call dyn_debug_print(debugout_info, 'Inquiring local and global mesh dimensions')
        ! Inquire local and global mesh dimensions.
        call dyn_inquire_mesh_dimensions()
        ! Check for consistency in numbers of vertical layers.
        if (nvertlevels /= pver) then
            call dyn_debug_print(debugout_verbose, 'Number of vertical layers in CAM-SIMA namelist, pver = ' // &
                stringify([pver]))
            call dyn_debug_print(debugout_verbose, 'Number of vertical layers in initial file, nvertlevels = ' // &
                stringify([nvertlevels]))
            call endrun('Numbers of vertical layers mismatch', subname, __LINE__)
        end if
        call dyn_debug_print(debugout_info, 'Initializing reference pressure')
        ! Initialize reference pressure for use by physics.
        call init_reference_pressure()
        call dyn_debug_print(debugout_info, 'Initializing physics grid')
        ! Initialize physics grid.
        call init_physics_grid()
        call dyn_debug_print(debugout_info, 'Registering dynamics grid with CAM-SIMA')
        ! Register dynamics grid with CAM-SIMA.
        call define_cam_grid()
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine model_grid_init
Call graph
model_grid_init calls dynconst_init, endrun, initial_file_get_id, dyn_debug_print, define_cam_grid, dyn_inquire_mesh_dimensions, dyn_mpas_compute_unit_vector, dyn_mpas_init_phase3, dyn_mpas_read_write_stream, init_physics_grid, init_reference_pressure, stringify, vert_coord_init, model_grid_init
dyn_debug_print calls dyn_debug_print, stringify
define_cam_grid calls dyn_debug_print, stringify, cam_grid_attribute_register, cam_grid_register, check_allocate, horiz_coord_create, dyn_grid_id, get_variable_pointer
dyn_inquire_mesh_dimensions calls dyn_debug_print, stringify, dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension
dyn_mpas_compute_unit_vector calls mpas_initialize_vectors, get_variable_pointer, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer
dyn_mpas_init_phase3 calls mpas_bootstrap_framework_phase1, mpas_bootstrap_framework_phase2, mpas_pool_add_config, mpas_pool_add_dimension, mpas_pool_get_dimension, pio_file_is_open, dyn_mpas_debug_print, dyn_mpas_get_pool_pointer, stringify
dyn_mpas_read_write_stream calls mpas_closestream, mpas_pool_destroy_pool, mpas_readstream, mpas_writestream, postread_reindex, postwrite_reindex, prewrite_reindex, dyn_mpas_debug_print, dyn_mpas_exchange_halo, dyn_mpas_init_stream_with_pool, parse_stream_name
init_physics_grid calls dyn_debug_print, stringify, check_allocate, coord_indices, dyn_block_index, get_variable_pointer, phys_grid_init
init_reference_pressure calls dyn_debug_print, stringify, add_vert_coord, check_allocate, dzw_of_rdzw, reverse, zu_of_dzw, zw_of_dzw, get_variable_pointer, ref_pres_init, std_atm_pres
dyn_grid_id calls dyn_grid_id
dzw_of_rdzw calls dzw_of_rdzw_real32, dzw_of_rdzw_real64
reverse calls reverse_real32, reverse_real64
zu_of_dzw calls zu_of_dzw_real32, zu_of_dzw_real64
zw_of_dzw calls zw_of_dzw_real32, zw_of_dzw_real64
dyn_mpas_debug_print calls stringify
dyn_mpas_exchange_halo calls dyn_mpas_debug_print, stringify, mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info
dyn_mpas_get_global_mesh_dimension calls get_variable_pointer, dyn_mpas_debug_print, mpas_dmpar_max_int, mpas_dmpar_sum_int
dyn_mpas_get_local_mesh_dimension calls get_variable_pointer, dyn_mpas_debug_print
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool
dyn_mpas_init_stream_with_pool calls mpas_pool_add_config, pio_file_is_open, dyn_mpas_debug_print, parse_stream_name, stringify, mpas_createstream, mpas_pool_create_pool, mpas_pool_get_field, mpas_streamaddfield, add_stream_attribute, dyn_mpas_check_variable_status
parse_stream_name calls tokenize, index_unique, parse_stream_name_fragment
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
dyn_mpas_check_variable_status calls pio_file_is_open, dyn_mpas_debug_print, stringify, mpas_pool_get_field, constituentnames, pio_inq_varid, pio_inq_varndims, pio_inq_vartype
dyn_mpas_get_variable_pointer_c0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_c1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_dimension, dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_dimension, dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_i3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_l0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r0 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array, mpas_pool_get_config
dyn_mpas_get_variable_pointer_r1 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r2 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r3 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r4 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
dyn_mpas_get_variable_pointer_r5 calls dyn_mpas_get_pool_pointer, mpas_pool_get_array
zu_of_dzw_real32 calls zw_of_dzw
zu_of_dzw_real64 calls zw_of_dzw
tokenize_into_first_last calls split
tokenize_into_tokens_separator calls tokenize
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64