parse_stream_name – MPAS Dynamical Core
parse_stream_name Function
29 statements
Source File
private pure function parse_stream_name(stream_name) result(var_info_list)
Uses
dyn_mpas_procedures
Parse a stream name, which consists of one or more stream name fragments, and return the corresponding variable information as a list of var_info_type. Multiple stream name fragments should be separated by "+" (i.e., a plus, meaning "addition" operation) or "-" (i.e., a minus, meaning "subtraction" operation). A stream name fragment can be a predefined stream name (e.g., "invariant", "input", etc.) or a single variable name. For example, a stream name of "invariant+input+restart" means the union of variables in the "invariant", "input", and "restart" streams. Duplicate variable information in the resulting list is discarded. (KCW, 2024-06-01)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: stream_name
Return Value type(var_info_type), allocatable, (:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: j
character(len=:), private, allocatable :: stream_name_fragment(:)
character(len=:), private, allocatable :: stream_name_operator(:)
character(len=*), private, parameter :: supported_stream_name_operator = '+-'
type(var_info_type), private, allocatable :: var_info_list_buffer(:)
character(len=len(invariant_var_info_list%name)), private, allocatable :: var_name_list(:)
Source Code
    pure function parse_stream_name(stream_name) result(var_info_list)
        ! Module(s) from MPAS.
        use dyn_mpas_procedures, only: index_unique, tokenize
        character(*), intent(in) :: stream_name
        type(var_info_type), allocatable :: var_info_list(:)
        character(*), parameter :: supported_stream_name_operator = '+-'
        character(:), allocatable :: stream_name_fragment(:), stream_name_operator(:)
        character(len(invariant_var_info_list % name)), allocatable :: var_name_list(:)
        integer :: i, j
        type(var_info_type), allocatable :: var_info_list_buffer(:)
        call tokenize(stream_name, supported_stream_name_operator, stream_name_fragment, stream_name_operator)
        var_info_list = parse_stream_name_fragment(stream_name_fragment(1))
        do i = 2, size(stream_name_fragment)
            ! Process the stream name fragment according to the operator.
            var_info_list_buffer = parse_stream_name_fragment(stream_name_fragment(i))
            if (size(var_info_list_buffer) > 0) then
                select case (stream_name_operator(i - 1))
                    case ('+')
                        var_info_list = [var_info_list, var_info_list_buffer]
                    case ('-')
                        do j = 1, size(var_info_list_buffer)
                            var_name_list = var_info_list % name
                            var_info_list = pack(var_info_list, var_name_list /= var_info_list_buffer(j) % name)
                        end do
                    case default
                        ! Do nothing for unknown operators. Should not happen at all.
                end select
            end if
        end do
        ! Discard duplicate variable information by names.
        var_name_list = var_info_list % name
        var_info_list = var_info_list(index_unique(var_name_list))
    end function parse_stream_name
Call graph
parse_stream_name calls tokenize, index_unique, parse_stream_name_fragment
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
tokenize_into_first_last calls split
tokenize_into_tokens_separator calls tokenize
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final