reverse_real32 – MPAS Dynamical Core
reverse_real32 Function
11 statements
Source File
private pure function reverse_real32(array) result(reverse)
Uses
iso_fortran_env
Reverse the order of elements in array. Single precision variant. (KCW, 2024-07-17)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: array(:)
Return Value real(kind=real32), (size(array))
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: n
Source Code
    pure function reverse_real32(array) result(reverse)
        use, intrinsic :: iso_fortran_env, only: real32
        real(real32), intent(in) :: array(:)
        real(real32) :: reverse(size(array))
        integer :: n
        n = size(array)
        ! There is nothing to reverse.
        if (n == 0) then
            return
        end if
        reverse(:) = array(n:1:-1)
    end function reverse_real32
Call graph
reverse calls reverse_real32
dyn_exchange_constituent_states calls reverse, dyn_exchange_constituent_states
init_reference_pressure calls reverse
dynamics_to_physics_coupling calls set_physics_state_column, dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
model_grid_init calls init_reference_pressure, model_grid_init
physics_to_dynamics_coupling calls set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru, dyn_exchange_constituent_states, physics_to_dynamics_coupling
set_analytic_initial_condition calls init_shared_variables, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_u
dyn_init calls dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
stepon_run2 calls physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling