rho_by_equation_of_state – MPAS Dynamical Core
rho_by_equation_of_state Function
6 statements
Source File
public pure elemental function rho_by_equation_of_state(constant_r, p, t) result(rho)
Uses
iso_fortran_env
Compute the density rho from the pressure p and the temperature t by equation of state. Essentially, . Equation of state may take other forms, such as , , . Choose wisely which form to use. (KCW, 2025-07-10)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_r
real(kind=real64), intent(in) :: p
real(kind=real64), intent(in) :: t
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function rho_by_equation_of_state(constant_r, p, t) result(rho)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_r, p, t
        real(real64) :: rho
        rho = p / (constant_r * t)
    end function rho_by_equation_of_state
Call graph
set_analytic_initial_condition calls set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta
dyn_init calls set_analytic_initial_condition, dyn_init