set_thermodynamic_energy_formula – MPAS Dynamical Core
set_thermodynamic_energy_formula Subroutine
10 statements
Source File
subroutine set_thermodynamic_energy_formula()
Uses
cam_thermo_formula
cam_logfile
physics_types
Set the thermodynamic energy formula of dynamical core to MPAS. (KCW, 2025-07-17)
Arguments
None
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=*), private, parameter :: subname = 'dyn_comp::set_thermodynamic_energy_formula'
Source Code
    subroutine set_thermodynamic_energy_formula()
        ! Module(s) from CAM-SIMA.
        use cam_logfile, only: debugout_debug
        use cam_thermo_formula, only: energy_formula_dycore, energy_formula_dycore_mpas
        use physics_types, only: dycore_energy_consistency_adjust
        character(*), parameter :: subname = 'dyn_comp::set_thermodynamic_energy_formula'
        call dyn_debug_print(debugout_debug, subname // ' entered')
        ! Set the thermodynamic energy formula of dynamical core to MPAS for use in `cam_thermo`.
        energy_formula_dycore = energy_formula_dycore_mpas
        ! The total energy of dynamical core, which uses "MPAS formula" as set above, is not consistent with
        ! that of CAM physics, which uses "FV formula". Therefore, temperature and temperature tendency adjustments
        ! are needed at the end of each physics time step.
        dycore_energy_consistency_adjust = .true.
        call dyn_debug_print(debugout_debug, subname // ' completed')
    end subroutine set_thermodynamic_energy_formula
Call graph
set_thermodynamic_energy_formula calls dyn_debug_print
dyn_debug_print calls dyn_debug_print, stringify
dyn_init calls set_thermodynamic_energy_formula, dyn_init