split – MPAS Dynamical Core
split Subroutine
20 statements
Source File
public pure subroutine split(string, set, pos, back)
Parse a string into tokens, one at a time. Each character in set is a token delimiter. If back is absent or is present with the value .false., pos is assigned the position of the leftmost token delimiter in string whose position is greater than pos, or if there is no such character, it is assigned a value one greater than the length of string. This identifies a token with starting position one greater than the value of pos on invocation, and ending position one less than the value of pos on return. If back is present with the value .true., pos is assigned the position of the rightmost token delimiter in string whose position is less than pos, or if there is no such character, it is assigned the value zero. This identifies a token with ending position one less than the value of pos on invocation, and starting position one greater than the value of pos on return. This subroutine implements the split intrinsic procedure as defined in the Fortran 2023 language standard (Section 16.9.196). We implement it ourselves because the compiler support may take years to become widespread. (KCW, 2025-10-29)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: set
integer, intent(inout) :: pos
logical, intent(in), optional :: back
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: offset
Source Code
    pure subroutine split(string, set, pos, back)
        character(*), intent(in) :: string, set
        integer, intent(inout) :: pos
        logical, optional, intent(in) :: back
        integer :: offset
        if (present(back)) then
            if (back) then
                offset = clamp(pos, 1, len(string) + 1)
                pos = scan(string(1:offset - 1), set, back=.true.)
                return
            end if
        end if
        offset = clamp(pos, 0, len(string))
        pos = scan(string(offset + 1:), set)
        if (pos == 0) then
            pos = len(string) + 1
            return
        end if
        pos = offset + pos
    end subroutine split
Call graph
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
tokenize_into_first_last calls split
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
parse_stream_name calls tokenize
tokenize_into_tokens_separator calls tokenize
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final