stepon_run2 – MPAS Dynamical Core
stepon_run2 Subroutine
12 statements
Source File
public subroutine stepon_run2(cam_runtime_opts, phys_state, phys_tend, dyn_in, dyn_out)
Uses
runtime_obj
dyn_comp
dyn_coupling
physics_types
Arguments
Type Intent Optional Attributes Name
type(runtime_options), intent(in) :: cam_runtime_opts
type(physics_state), intent(in) :: phys_state
type(physics_tend), intent(in) :: phys_tend
type(dyn_import_t), intent(in) :: dyn_in
type(dyn_export_t), intent(in) :: dyn_out
Calls
Source Code
    subroutine stepon_run2(cam_runtime_opts, phys_state, phys_tend, dyn_in, dyn_out)
        ! Module(s) from CAM-SIMA.
        use dyn_comp, only: dyn_export_t, dyn_import_t
        use dyn_coupling, only: physics_to_dynamics_coupling
        use physics_types, only: physics_state, physics_tend
        use runtime_obj, only: runtime_options
        type(runtime_options), intent(in) :: cam_runtime_opts
        type(physics_state), intent(in) :: phys_state
        type(physics_tend), intent(in) :: phys_tend
        type(dyn_import_t), intent(in) :: dyn_in
        type(dyn_export_t), intent(in) :: dyn_out
        call physics_to_dynamics_coupling()
    end subroutine stepon_run2
Call graph
stepon_run2 calls physics_to_dynamics_coupling
physics_to_dynamics_coupling calls physics_to_dynamics_coupling, dyn_debug_print, dyn_exchange_constituent_states, final_shared_variables, init_shared_variables, set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, set_mpas_physics_tendency_ru
dyn_debug_print calls dyn_debug_print, stringify
dyn_exchange_constituent_states calls dyn_exchange_constituent_states, dyn_debug_print, check_allocate, reverse, get_variable_pointer, dyn_mpas_exchange_halo, cam_advected_constituents_array, const_is_dry, const_is_water_species, endrun, pdel, pdeldry, dyn_mpas_map_constituent_index, dyn_mpas_map_mpas_scalar_index
reverse calls reverse_real32, reverse_real64
dyn_mpas_compute_edge_wind calls get_variable_pointer, dyn_mpas_exchange_halo, dyn_mpas_debug_print
dyn_mpas_exchange_halo calls mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info, dyn_mpas_debug_print, stringify
dyn_mpas_debug_print calls stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool