stepon_timestep_init – MPAS Dynamical Core
stepon_timestep_init Subroutine
16 statements
Source File
public subroutine stepon_timestep_init(dtime_phys, cam_runtime_opts, phys_state, phys_tend, dyn_in, dyn_out)
Uses
ccpp_kinds
runtime_obj
time_manager
physics_types
dyn_comp
dyn_coupling
Arguments
Type Intent Optional Attributes Name
real(kind=kind_phys), intent(out) :: dtime_phys
type(runtime_options), intent(in) :: cam_runtime_opts
type(physics_state), intent(in) :: phys_state
type(physics_tend), intent(in) :: phys_tend
type(dyn_import_t), intent(in) :: dyn_in
type(dyn_export_t), intent(in) :: dyn_out
Calls
Source Code
    subroutine stepon_timestep_init(dtime_phys, cam_runtime_opts, phys_state, phys_tend, dyn_in, dyn_out)
        ! Module(s) from CAM-SIMA.
        use dyn_comp, only: dyn_export_t, dyn_import_t
        use dyn_coupling, only: dynamics_to_physics_coupling
        use physics_types, only: physics_state, physics_tend
        use runtime_obj, only: runtime_options
        use time_manager, only: get_step_size
        ! Module(s) from CCPP.
        use ccpp_kinds, only: kind_phys
        real(kind_phys), intent(out) :: dtime_phys
        type(runtime_options), intent(in) :: cam_runtime_opts
        type(physics_state), intent(in) :: phys_state
        type(physics_tend), intent(in) :: phys_tend
        type(dyn_import_t), intent(in) :: dyn_in
        type(dyn_export_t), intent(in) :: dyn_out
        ! Set timestep for physics.
        dtime_phys = real(get_step_size(), kind_phys)
        call dynamics_to_physics_coupling()
    end subroutine stepon_timestep_init
Call graph
stepon_timestep_init calls get_step_size, dynamics_to_physics_coupling
dynamics_to_physics_coupling calls dynamics_to_physics_coupling, dyn_debug_print, dyn_exchange_constituent_states, final_shared_variables, init_shared_variables, set_physics_state_column, set_physics_state_external, update_shared_variables
dyn_debug_print calls dyn_debug_print, stringify
dyn_exchange_constituent_states calls dyn_exchange_constituent_states, dyn_debug_print, check_allocate, const_is_water_species, endrun, reverse, get_variable_pointer, pdel, pdeldry, dyn_mpas_map_constituent_index, dyn_mpas_map_mpas_scalar_index, cam_advected_constituents_array, const_is_dry, dyn_mpas_exchange_halo
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
exner_function calls exner_function_of_cpd_p0_rd_p, exner_function_of_kappa_p0_p
reverse calls reverse_real32, reverse_real64
dyn_mpas_exchange_halo calls mpas_dmpar_exch_halo_field, mpas_pool_get_field, mpas_pool_get_field_info, dyn_mpas_debug_print, stringify
dyn_mpas_get_variable_pointer_c0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_c1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i0 calls mpas_pool_get_array, mpas_pool_get_config, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i1 calls mpas_pool_get_array, mpas_pool_get_dimension, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_i3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_l0 calls mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r0 calls mpas_pool_get_array, mpas_pool_get_config, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r1 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r2 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r3 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r4 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_get_variable_pointer_r5 calls mpas_pool_get_array, dyn_mpas_get_pool_pointer
dyn_mpas_debug_print calls stringify
dyn_mpas_get_pool_pointer calls mpas_pool_get_subpool