stringify – MPAS Dynamical Core
stringify Function
78 statements
Source File
public pure function stringify(value, separator)
Uses
iso_fortran_env
Convert one or more values of any intrinsic data types to a character string for pretty printing. If value contains more than one element, the elements will be stringified, delimited by separator, then concatenated. If value contains exactly one element, the element will be stringified without using separator. If value contains zero element or is of unsupported data types, an empty character string is produced. If separator is not supplied, it defaults to ", " (i.e., a comma and a space). (KCW, 2024-02-04)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: value(:)
character(len=*), intent(in), optional :: separator
Return Value character(len=:), allocatable
Called by
Variables
Type Visibility Attributes Name Initial
character(len=:), private, allocatable :: buffer
character(len=:), private, allocatable :: delimiter
character(len=:), private, allocatable :: format
integer, private :: i
integer, private :: n
integer, private :: offset
integer, private, parameter :: sizelimit = 1024
character(len=:), private, allocatable :: value_c(:)
Source Code
    pure function stringify(value, separator)
        use, intrinsic :: iso_fortran_env, only: int32, int64, real32, real64
        class(*), intent(in) :: value(:)
        character(*), optional, intent(in) :: separator
        character(:), allocatable :: stringify
        integer, parameter :: sizelimit = 1024
        character(:), allocatable :: buffer, delimiter, format
        character(:), allocatable :: value_c(:)
        integer :: i, n, offset
        if (present(separator)) then
            delimiter = separator
        else
            delimiter = ', '
        end if
        n = min(size(value), sizelimit)
        if (n == 0) then
            stringify = ''
            return
        end if
        select type (value)
            type is (character(*))
                allocate(character(len(value) * n + len(delimiter) * (n - 1)) :: buffer)
                buffer(:) = ''
                offset = 0
                ! Workaround for a bug in GNU Fortran >= 12. This is perhaps the manifestation of GCC Bugzilla Bug 100819.
                ! When a character string array is passed as the actual argument to an unlimited polymorphic dummy argument,
                ! its array index and length parameter are mishandled.
                allocate(character(len(value)) :: value_c(size(value)))
                value_c(:) = value(:)
                do i = 1, n
                    if (len(delimiter) > 0 .and. i > 1) then
                        buffer(offset + 1:offset + len(delimiter)) = delimiter
                        offset = offset + len(delimiter)
                    end if
                    if (len_trim(adjustl(value_c(i))) > 0) then
                        buffer(offset + 1:offset + len_trim(adjustl(value_c(i)))) = trim(adjustl(value_c(i)))
                        offset = offset + len_trim(adjustl(value_c(i)))
                    end if
                end do
                deallocate(value_c)
            type is (integer(int32))
                allocate(character(11 * n + len(delimiter) * (n - 1)) :: buffer)
                allocate(character(17 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                write(format, '(a, i0, 3a)') '(ss, ', n, '(i0, :, "', delimiter, '"))'
                write(buffer, format) value
            type is (integer(int64))
                allocate(character(20 * n + len(delimiter) * (n - 1)) :: buffer)
                allocate(character(17 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                write(format, '(a, i0, 3a)') '(ss, ', n, '(i0, :, "', delimiter, '"))'
                write(buffer, format) value
            type is (logical)
                allocate(character(1 * n + len(delimiter) * (n - 1)) :: buffer)
                allocate(character(13 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                write(format, '(a, i0, 3a)') '(', n, '(l1, :, "', delimiter, '"))'
                write(buffer, format) value
            type is (real(real32))
                allocate(character(13 * n + len(delimiter) * (n - 1)) :: buffer)
                if (maxval(abs(value)) < 1.0e5_real32) then
                    allocate(character(20 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                    write(format, '(a, i0, 3a)') '(ss, ', n, '(f13.6, :, "', delimiter, '"))'
                else
                    allocate(character(23 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                    write(format, '(a, i0, 3a)') '(ss, ', n, '(es13.6e2, :, "', delimiter, '"))'
                end if
                write(buffer, format) value
            type is (real(real64))
                allocate(character(13 * n + len(delimiter) * (n - 1)) :: buffer)
                if (maxval(abs(value)) < 1.0e5_real64) then
                    allocate(character(20 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                    write(format, '(a, i0, 3a)') '(ss, ', n, '(f13.6, :, "', delimiter, '"))'
                else
                    allocate(character(23 + len(delimiter) + floor(log10(real(n))) + 1) :: format)
                    write(format, '(a, i0, 3a)') '(ss, ', n, '(es13.6e2, :, "', delimiter, '"))'
                end if
                write(buffer, format) value
            class default
                stringify = ''
                return
        end select
        stringify = trim(buffer)
    end function stringify
Call graph
dyn_mpas_check_variable_status calls stringify, dyn_mpas_debug_print
dyn_mpas_compute_cell_relative_vorticity calls stringify
dyn_mpas_debug_print calls stringify
dyn_mpas_define_scalar calls stringify, dyn_mpas_debug_print
dyn_mpas_exchange_halo calls stringify, dyn_mpas_debug_print
dyn_mpas_get_variable_value_c0 calls stringify
dyn_mpas_get_variable_value_c1 calls stringify
dyn_mpas_get_variable_value_i0 calls stringify
dyn_mpas_get_variable_value_i1 calls stringify
dyn_mpas_get_variable_value_i2 calls stringify
dyn_mpas_get_variable_value_i3 calls stringify
dyn_mpas_get_variable_value_l0 calls stringify
dyn_mpas_get_variable_value_r0 calls stringify
dyn_mpas_get_variable_value_r1 calls stringify
dyn_mpas_get_variable_value_r2 calls stringify
dyn_mpas_get_variable_value_r3 calls stringify
dyn_mpas_get_variable_value_r4 calls stringify
dyn_mpas_get_variable_value_r5 calls stringify
dyn_mpas_init_phase1 calls stringify, dyn_mpas_debug_print
dyn_mpas_init_phase3 calls stringify, dyn_mpas_debug_print
dyn_mpas_init_phase4 calls stringify, dyn_mpas_debug_print
dyn_mpas_init_stream_with_pool calls stringify, dyn_mpas_check_variable_status, dyn_mpas_debug_print, add_stream_attribute
dyn_mpas_read_namelist calls stringify, dyn_mpas_debug_print
dyn_mpas_run calls stringify, dyn_mpas_debug_print
dyn_exchange_constituent_states calls dyn_mpas_exchange_halo, dyn_exchange_constituent_states
dyn_init calls dyn_mpas_define_scalar, dyn_mpas_init_phase4, dyn_mpas_read_write_stream, dyn_exchange_constituent_states, set_analytic_initial_condition, dyn_init
dyn_mpas_compute_edge_wind calls dyn_mpas_debug_print, dyn_mpas_exchange_halo
dyn_mpas_compute_unit_vector calls dyn_mpas_debug_print
dyn_mpas_final calls dyn_mpas_debug_print
dyn_mpas_get_global_mesh_dimension calls dyn_mpas_debug_print
dyn_mpas_get_local_mesh_dimension calls dyn_mpas_debug_print
dyn_mpas_init_phase2 calls dyn_mpas_debug_print
dyn_mpas_read_write_stream calls dyn_mpas_debug_print, dyn_mpas_exchange_halo, dyn_mpas_init_stream_with_pool
dyn_readnl calls dyn_mpas_init_phase1, dyn_mpas_read_namelist, dyn_mpas_init_phase2, dyn_readnl
dyn_run calls dyn_mpas_run, dyn_run
dyn_variable_dump calls dyn_mpas_exchange_halo, dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_init_phase3, dyn_mpas_compute_unit_vector, dyn_mpas_read_write_stream, dyn_inquire_mesh_dimensions, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
dyn_inquire_mesh_dimensions calls dyn_mpas_get_global_mesh_dimension, dyn_mpas_get_local_mesh_dimension, dyn_inquire_mesh_dimensions
physics_to_dynamics_coupling calls set_mpas_physics_tendency_rho, set_mpas_physics_tendency_rtheta, dyn_exchange_constituent_states, set_mpas_physics_tendency_ru, physics_to_dynamics_coupling
set_analytic_initial_condition calls set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta, set_mpas_state_scalars, set_mpas_state_w, set_mpas_state_u
dynamics_to_physics_coupling calls dyn_exchange_constituent_states, set_physics_state_external, dynamics_to_physics_coupling
stepon_run3 calls dyn_run
stepon_final calls dyn_final
stepon_run2 calls physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling