t_of_tm_qv – MPAS Dynamical Core
t_of_tm_qv Function
6 statements
Source File
public pure elemental function t_of_tm_qv(constant_rd, constant_rv, tm, qv) result(t)
Uses
iso_fortran_env
Compute the temperature t as a function of the modified moist temperature tm and the water vapor mixing ratio qv. Essentially, . This modified "moist" temperature is described herein: The paragraph below equation 2.7 in doi:10.5065/1DFH-6P97. The paragraph below equation 2 in doi:10.1175/MWR-D-11-00215.1. Similarly, it can be shown that the relation, , also holds. (KCW, 2025-07-10)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_rd
real(kind=real64), intent(in) :: constant_rv
real(kind=real64), intent(in) :: tm
real(kind=real64), intent(in) :: qv
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function t_of_tm_qv(constant_rd, constant_rv, tm, qv) result(t)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_rd, constant_rv, tm, qv
        real(real64) :: t
        t = tm / (1.0_real64 + constant_rv / constant_rd * qv)
    end function t_of_tm_qv
Call graph
dynamics_to_physics_coupling calls update_shared_variables, dynamics_to_physics_coupling
physics_to_dynamics_coupling calls set_mpas_physics_tendency_rtheta, physics_to_dynamics_coupling
stepon_run2 calls physics_to_dynamics_coupling
stepon_timestep_init calls dynamics_to_physics_coupling