theta_by_poisson_equation – MPAS Dynamical Core
theta_by_poisson_equation Function
6 statements
Source File
public pure elemental function theta_by_poisson_equation(constant_cpd, constant_p0, constant_rd, t, p) result(theta)
Uses
iso_fortran_env
Compute the potential temperature theta at reference pressure p0 from the temperature t at pressure p by Poisson equation. Essentially, . (KCW, 2024-07-02)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_cpd
real(kind=real64), intent(in) :: constant_p0
real(kind=real64), intent(in) :: constant_rd
real(kind=real64), intent(in) :: t
real(kind=real64), intent(in) :: p
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function theta_by_poisson_equation(constant_cpd, constant_p0, constant_rd, t, p) result(theta)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_cpd, constant_p0, constant_rd, t, p
        real(real64) :: theta
        theta = t * ((constant_p0 / p) ** (constant_rd / constant_cpd))
    end function theta_by_poisson_equation
Call graph
set_analytic_initial_condition calls set_mpas_state_rho_base_theta_base, set_mpas_state_rho_theta
dyn_init calls set_analytic_initial_condition, dyn_init