tm_of_t_qv – MPAS Dynamical Core
tm_of_t_qv Function
6 statements
Source File
public pure elemental function tm_of_t_qv(constant_rd, constant_rv, t, qv) result(tm)
Uses
iso_fortran_env
Compute the modified moist temperature tm as a function of the temperature t and the water vapor mixing ratio qv. Essentially, . This modified "moist" temperature is described herein: The paragraph below equation 2.7 in doi:10.5065/1DFH-6P97. The paragraph below equation 2 in doi:10.1175/MWR-D-11-00215.1. Similarly, it can be shown that the relation, , also holds. (KCW, 2025-07-10)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: constant_rd
real(kind=real64), intent(in) :: constant_rv
real(kind=real64), intent(in) :: t
real(kind=real64), intent(in) :: qv
Return Value real(kind=real64)
Called by
Source Code
    pure elemental function tm_of_t_qv(constant_rd, constant_rv, t, qv) result(tm)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: constant_rd, constant_rv, t, qv
        real(real64) :: tm
        tm = t * (1.0_real64 + constant_rv / constant_rd * qv)
    end function tm_of_t_qv
Call graph
physics_to_dynamics_coupling calls set_mpas_physics_tendency_rtheta, physics_to_dynamics_coupling
set_analytic_initial_condition calls set_mpas_state_rho_theta
dyn_init calls set_analytic_initial_condition, dyn_init
stepon_run2 calls physics_to_dynamics_coupling