tokenize_into_first_last – MPAS Dynamical Core
tokenize_into_first_last Subroutine
18 statements
Source File
private pure subroutine tokenize_into_first_last(string, set, first, last)
Parse a string into tokens. Each character in set is a token delimiter. first is allocated with the lower bound equal to one and the upper bound equal to the number of tokens in string. Each element is assigned, in array element order, the starting position of each token in string, in the order found. last is allocated with the lower bound equal to one and the upper bound equal to the number of tokens in string. Each element is assigned, in array element order, the ending position of each token in string, in the order found. This subroutine implements the tokenize intrinsic procedure as defined in the Fortran 2023 language standard (Section 16.9.210). We implement it ourselves because the compiler support may take years to become widespread. (KCW, 2025-10-29)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: set
integer, intent(out), allocatable :: first(:)
integer, intent(out), allocatable :: last(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: l
integer, private :: n
integer, private :: pos
integer, private :: pos_end(len(string)+1)
integer, private :: pos_start(len(string)+1)
Source Code
    pure subroutine tokenize_into_first_last(string, set, first, last)
        character(*), intent(in) :: string, set
        integer, allocatable, intent(out) :: first(:), last(:)
        integer :: pos_start(len(string) + 1), pos_end(len(string) + 1)
        integer :: l, n, pos
        l = len(string)
        n = 0
        pos = 0
        do while (pos < l + 1)
            n = n + 1
            pos_start(n) = pos + 1
            call split(string, set, pos)
            pos_end(n) = pos - 1
        end do
        allocate(first(n), last(n))
        first(:) = pos_start(1:n)
        last(:) = pos_end(1:n)
    end subroutine tokenize_into_first_last
Call graph
tokenize_into_first_last calls split
split calls clamp
clamp calls clamp_int32, clamp_int64, clamp_real32, clamp_real64
tokenize calls tokenize_into_first_last, tokenize_into_tokens_separator
parse_stream_name calls tokenize
tokenize_into_tokens_separator calls tokenize
dyn_mpas_init_stream_with_pool calls parse_stream_name
dyn_mpas_read_write_stream calls parse_stream_name, dyn_mpas_init_stream_with_pool
dyn_init calls dyn_mpas_read_write_stream, dyn_init
dyn_variable_dump calls dyn_mpas_read_write_stream
model_grid_init calls dyn_mpas_read_write_stream, model_grid_init
dyn_final calls dyn_variable_dump, dyn_final
stepon_final calls dyn_final