zw_of_dzw_real64 – MPAS Dynamical Core
zw_of_dzw_real64 Function
9 statements
Source File
private pure function zw_of_dzw_real64(dzw) result(zw)
Uses
iso_fortran_env
Compute the coordinates at w-wind levels zw from the differences in between w-wind levels dzw, where is the vertical coordinate, and w-wind levels are synonymous with layer interfaces in MPAS. (KCW, 2025-10-20)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: dzw(:)
Return Value real(kind=real64), (size(dzw)+1)
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: k
Source Code
    pure function zw_of_dzw_real64(dzw) result(zw)
        use, intrinsic :: iso_fortran_env, only: real64
        real(real64), intent(in) :: dzw(:)
        real(real64) :: zw(size(dzw) + 1)
        integer :: k
        do k = 1, size(zw)
            zw(k) = sum(dzw(1:k - 1))
        end do
    end function zw_of_dzw_real64
Call graph
zw_of_dzw calls zw_of_dzw_real64
init_reference_pressure calls zw_of_dzw, zu_of_dzw
zu_of_dzw_real32 calls zw_of_dzw
zu_of_dzw_real64 calls zw_of_dzw
zu_of_dzw calls zu_of_dzw_real32, zu_of_dzw_real64
model_grid_init calls init_reference_pressure, model_grid_init