almost_equal – MPAS Dynamical Core
almost_equal Interface
4 statements
Source File
public interface almost_equal
Calls
Called by
Module Procedures
private pure elemental function almost_equal_real32(a, b, absolute_tolerance, relative_tolerance) result(almost_equal)
Test a and b for approximate equality, where a and b are both reals. (KCW, 2024-05-25)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: a
real(kind=real32), intent(in) :: b
real(kind=real32), intent(in), optional :: absolute_tolerance
real(kind=real32), intent(in), optional :: relative_tolerance
Return Value logical
private pure elemental function almost_equal_real64(a, b, absolute_tolerance, relative_tolerance) result(almost_equal)
Test a and b for approximate equality, where a and b are both reals. (KCW, 2024-05-25)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: a
real(kind=real64), intent(in) :: b
real(kind=real64), intent(in), optional :: absolute_tolerance
real(kind=real64), intent(in), optional :: relative_tolerance
Return Value logical
Call graph
almost_equal calls almost_equal_real32, almost_equal_real64
almost_divisible_real32 calls almost_equal
almost_divisible_real64 calls almost_equal
check_topography_data calls almost_equal
almost_divisible calls almost_divisible_real32, almost_divisible_real64
dyn_init calls check_topography_data, dyn_mpas_init_phase4, dyn_init
dyn_mpas_init_phase4 calls almost_divisible