almost_divisible – MPAS Dynamical Core
almost_divisible Interface
4 statements
Source File
public interface almost_divisible
Calls
Called by
Module Procedures
private pure elemental function almost_divisible_real32(a, b) result(almost_divisible)
Test if a is divisible by b, where a and b are both reals. (KCW, 2024-05-25)
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in) :: a
real(kind=real32), intent(in) :: b
Return Value logical
private pure elemental function almost_divisible_real64(a, b) result(almost_divisible)
Test if a is divisible by b, where a and b are both reals. (KCW, 2024-05-25)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: a
real(kind=real64), intent(in) :: b
Return Value logical
Call graph
almost_divisible calls almost_divisible_real32, almost_divisible_real64
almost_divisible_real32 calls almost_equal
almost_divisible_real64 calls almost_equal
almost_equal calls almost_equal_real32, almost_equal_real64
dyn_mpas_init_phase4 calls almost_divisible
dyn_init calls dyn_mpas_init_phase4, dyn_init