dyn_grid_id – MPAS Dynamical Core
dyn_grid_id Interface
13 statements
Source File
interface
Calls
Called by
public pure module function dyn_grid_id(name) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value integer
Call graph
dyn_grid_id calls dyn_grid_id
define_cam_grid calls dyn_grid_id
model_grid_init calls define_cam_grid, model_grid_init