name: docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        run: |
             sudo apt update
             sudo apt install -y python3 python3-venv python3-pip
             python3 -m venv myenv
             source myenv/bin/activate
             pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2
             echo "cache_id=$(date --utc '+%F')" >> $GITHUB_ENV

      - name: Configure cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy to gh-pages
        run: |
             source myenv/bin/activate
             mkdocs gh-deploy -b gh-pages --force

